### ISSUE TITLE
Fallback support for WP Custom Avatar

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#103]
WP Custom Avatar shows a broken image for Client Users with no avatar

We probably need to use a fallback image
![client-user-no-photo](https://user-images.githubusercontent.com/26938537/28165375-87c75348-67a1-11e7-92cd-9dc55b53b640.jpg)

**Comment by deenison** [comment]
Is this issue still valid given that we changed how Client Users work? @upstreamplugin

**Comment by upstreamplugin** [comment]
No, should be all fixed now
