### ISSUE TITLE
Clearer error highlighting

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#104]
If you make a mistake saving a project or client, we don't gave any indication that the save failed.

For example, I tried to save a Client User with a duplicate email and it took me several minutes to bugshoot. 

Here was the problem input. Absolutely nothing seems to be wrong:
![screen shot 2017-07-13 at 8 39 57 am](https://user-images.githubusercontent.com/26938537/28166784-46251eba-67a7-11e7-95d2-b73259d7f4e3.png)

So, we probably need an error message, and also a red highlight for the problem input

**Comment by deenison** [comment]
This issue is no longer valid since [v1.11.0](https://github.com/upstreamplugin/UpStream/releases/tag/v1.11.0) due recent changes made on issue #85.
