### ISSUE TITLE
Milestones are required, but not correctly

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#111]
On the frontend, Milestones are shown as required ...

![screen shot 2017-07-25 at 5 51 33 pm](https://user-images.githubusercontent.com/26938537/28595477-102a4f46-7162-11e7-9c12-568425e0605d.png)

But you can save a task without choosing a Milestone ...

![screen shot 2017-07-25 at 5 51 42 pm](https://user-images.githubusercontent.com/26938537/28595495-1b35706e-7162-11e7-8936-b3c7ce4e3714.png)

The problem is that the task doesn't get saved. It just vanishes.

**Comment by deenison** [comment]
Are milestones really required for tasks?

**Comment by upstreamplugin** [comment]
They don't need to be, but we currently show that they are required, with the *
