### ISSUE TITLE
"Add task" and "Add milestone" shows even for existing items

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#112]
Even if you're editing an item, you will see "Add"

![screen shot 2017-07-25 at 5 58 40 pm](https://user-images.githubusercontent.com/26938537/28595721-14fe3388-7163-11e7-809c-f898133fcbd7.png)
![screen shot 2017-07-25 at 5 59 03 pm](https://user-images.githubusercontent.com/26938537/28595720-14f21e72-7163-11e7-908d-d310843e57e1.png)

**Comment by deenison** [comment]
Closing the issue because it was moved to another repo.
