### ISSUE TITLE
Visual indicator for overdue projects

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#113]
At the moment you can set an "overdue" status manually, but that's confusing. 

Perhaps the statuses should be renamed, or we should tie them to the due date for the task.

**Comment by upstreamplugin** [comment]
A second request to make statuses more dynamic and useful:
"Can we automatically link statuses & percentages?"

**Comment by deenison** [comment]
for doc reasons, the second request was turned into an [issue #194](https://github.com/upstreamplugin/UpStream/issues/194)
