### ISSUE TITLE
Task 1, Task 2, Task 3 keep appearing

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#127]
Even in a project that's been around for a while, and have a title, "Task 1", "Task 2", "Task 3" etc keep appearing

![screen shot 2017-08-08 at 6 24 04 pm](https://user-images.githubusercontent.com/26938537/29097292-fe069800-7c66-11e7-8019-45bedfbf10ca.png)

**Comment by deenison** [comment]
Do they have a custom title set? Is there any way to reproduce this? @upstreamplugin

**Comment by upstreamplugin** [comment]
Yes, they have a custom title

One quick way to get this to happen is by deleting a task.

In this project, I had two tasks that looked great, with custom titles. I added a task, then deleted it ...
![screen shot 2017-08-16 at 5 10 45 pm](https://user-images.githubusercontent.com/26938537/29385494-ec305c02-82a5-11e7-9327-7e0ae012fb40.png)
