### ISSUE TITLE
Frontend Edit plugin loads CSS and JS

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#128]
It looks like the frontend edit plugin load both a CSS and JS file on all pages

/wp-content/plugins/upstream-frontend-edit/assets/css/upstream-frontend-edit.css
/wp-content/plugins/upstream-frontend-edit/assets/js/modal.min.js

Should we load those only when UpStream is in action?

**Comment by deenison** [comment]
Yes, absolutely. I'll review for any unnecessarily calls on our assets
