### ISSUE TITLE
UpStream breaks search results

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#132]
If you're logged in, and search for a word used inside UpStream, the search results will be broken

Sample screenshot attached
![screen shot 2017-08-19 at 11 46 56 am](https://user-images.githubusercontent.com/26938537/29488201-26a31a70-84d4-11e7-9e4e-47dae692b9de.png)

**Comment by deenison** [comment]
Unable to reproduce the bug described so far. Is there an online env where this can be seen?

**Comment by upstreamplugin** [comment]
It did break on my test site.

here's the original report: https://wordpress.org/support/topic/wp-search-results-page-format-will-break-if-one-of-its-results-is-from-upstream/

**Comment by deenison** [comment]
Got it, thanks.
