### ISSUE TITLE
Use Completed, not Finished

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#158]
let's be consistent and use "Completed":

![screen shot 2017-09-11 at 11 53 06 am](https://user-images.githubusercontent.com/26938537/30284052-da97a6d4-96e7-11e7-9291-96d28e91f8b7.png)

![screen shot 2017-09-11 at 11 53 51 am](https://user-images.githubusercontent.com/26938537/30284071-eb3e5f3c-96e7-11e7-99b7-3f297876ece3.png)

**Comment by upstreamplugin** [comment]
Sorry, still not quite right

![screen shot 2017-09-13 at 9 35 15 am](https://user-images.githubusercontent.com/26938537/30380196-eff7eeaa-9866-11e7-9388-8952b6f7e32d.png)
![screen shot 2017-09-13 at 9 35 09 am](https://user-images.githubusercontent.com/26938537/30380197-f0025cf0-9866-11e7-9070-2bdd1313d503.png)
![screen shot 2017-09-13 at 9 35 13 am](https://user-images.githubusercontent.com/26938537/30380198-f0046216-9866-11e7-81cf-d9dcdb332577.png)

**Comment by deenison** [comment]
The counter takes into account all statuses marked as Closed type in settings. Should we still rename it? @upstreamplugin 
![statuses](https://user-images.githubusercontent.com/1078316/30393016-1706fecc-9895-11e7-84b3-be0c6903d08d.png)

**Comment by upstreamplugin** [comment]
Ah, I see your point. We've got ourselves a little confused with all these similar names ... Closed, Completed, Finished

**Comment by deenison** [comment]
Perhaps would be a good idea to use `Open` & `Closed` as states instead of type of statuses, like GitHub does i.e. for issues

**Comment by upstreamplugin** [comment]
Yes, that's clearer

**Comment by deenison** [comment]
Since this will require a bit of work, I created another issue #161.

Should we use "Completed" on all of them attempting to avoid some confusion until #161 is fixed and released?
