### ISSUE TITLE
Upstream doesn't use WP date format

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#16]
Upstream doesn’t seem to follow the choice of date format in the WordPress core

**Comment by deenison** [comment]
Thanks @stevejburge. This seems to be an already identified bug with one of the libraries used by the plugin. There's already an [upcoming fix](https://github.com/CMB2/CMB2/pull/867) on their part, so I'll put the issue on hold for now

**Comment by westbourneintl** [comment]
Outdated, no longer relevant
