### ISSUE TITLE
Long file description breaks edit buttons

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#163]
Confirmed bug ... When a File's Description is too long, the Edit and Delete buttons stop working.
![screen shot 2017-09-18 at 7 15 34 am](https://user-images.githubusercontent.com/26938537/30539594-312db5e8-9c41-11e7-9277-8f2873dfa21f.png)

**Comment by deenison** [comment]
This issue was fixed on `v1.3.6` of the [Frontend Edit](https://upstreamplugin.com/extensions/frontend-edit) extension.
