### ISSUE TITLE
"Add Files" should be "Update File"

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#164]
If you edit an existing file, the text is "Add File" on the save button. This should be "Update File"

![screen shot 2017 09 18 at 7 19 13 am](https://user-images.githubusercontent.com/26938537/30539724-cdda8b96-9c41-11e7-9e0d-30e0ba3b98d8.png)

**Comment by upstreamplugin** [comment]
The same is true for Milestones, Bugs, Tasks

**Comment by deenison** [comment]
This issue seems already fixed on the current latest version (v1.3.7) of the [Frontend Edit](https://upstreamplugin.com/extensions/frontend-edit/) extension.
