### ISSUE TITLE
Can't edit tasks if due date is passed

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#169]
If the the due date for a task is passed, it can't be edited on the front-end

The pencil disappears and the task is greyed out

![screen shot 2017-09-19 at 1 35 34 pm](https://user-images.githubusercontent.com/26938537/30606625-495aca48-9d40-11e7-9f40-ac6e07eec05e.png)

**Comment by deenison** [comment]
It seems that the quotes and double-quotes are causing this bug, not the due dates. 
The issue is now patched on the next update from Frontend Edit extension.
