### ISSUE TITLE
Progress bars are broken

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#174]
The progress bars on the main projects page just don't change if Milestones are disabled:
![screen shot 2017-09-21 at 1 25 41 pm](https://user-images.githubusercontent.com/26938537/30709501-6e597510-9ed0-11e7-8df0-51c94570c254.png)

**Comment by upstreamplugin** [comment]
I think this may be related to this other progress bar issue with disabling features

https://github.com/upstreamplugin/UpStream/issues/173

**Comment by deenison** [comment]
The whole progress feature definitely needs some attention.

**Comment by stevejburge** [comment]
A second customer report on this

**Comment by awijasa** [comment]
Hello,

I was able to restore these progress bars by putting back this chunk of code from Upstream 1.11.5's /templates/assets/js/upstream.js:

// Progressbar
jQuery(document).ready(function($){
if (jQuery(".progress .progress-bar")[0]) {
    jQuery('.progress .progress-bar').progressbar();
}
});
// /Progressbar


// NProgress
jQuery(document).ready(function($){
if (typeof NProgress != 'undefined') {
    $(document).ready(function () {
        NProgress.start();
    });

    $(window).load(function () {
        NProgress.done();
    });
}
});

Thanks,

Adrian
