### ISSUE TITLE
Reporting a bug on /includes/admin/up-enqueues.php

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#180]
From a customer ...

I am reporting a bug on /includes/admin/up-enqueues.php (Upstream 1.12.1)

Line 54: wp_register_style( 'upstream-admin', $css_dir . 'upstream.css', UPSTREAM_VERSION);

It should be:

wp_register_style( 'upstream-admin', $css_dir . 'upstream.css', array(), UPSTREAM_VERSION);

Otherwise, the WordPress version will be used and the user may get the old and cached upstream.css from a previous version of Upstream. Unless he/she just upgraded WordPress from 4.8.1 to 4.8.2.

Please refer to the spec for wp_register_style here: https://developer.wordpress.org/reference/functions/wp_register_style/

Notice that UPSTREM_VERSION is currently being passed to the $deps parameter. Not $ver. As consequence, the WordPress version is being used as $ver for upstream.css.

**Comment by deenison** [comment]
Good catch, thanks.
