### ISSUE TITLE
Stop junk from accumulating in admin screens

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#189]
Can we stop this type of junk on the admin pages?

![screen shot 2017-10-12 at 1 48 00 pm](https://user-images.githubusercontent.com/26938537/31510930-144a0e24-af54-11e7-804c-cea056dd0d66.png)

**Comment by awijasa** [comment]
Hello,

Just want to pitch in my thoughts: I think Upstream shouldn't interfere with warnings and notices created by other plugins or themes. In this case, the BeTheme and Thrive Architect notices were not created by Upstream. So, Upstream shouldn't be responsible for them.

Let me know what you think.

Thanks,

@awijasa

**Comment by upstreamplugin** [comment]
Thanks @awijasa

I guess I've seen a lot of very noise WordPress sites where the admin notices drown out the User Interface.

Maybe I need to do some testing and see how other WordPress plugins handle all these notices?

**Comment by deenison** [comment]
Thanks @awijasa, and I'm leaning to agree with you on this one. 

Would be great to have clean screens, unfortunately even if some extensions/themes might toss annoying alerts and warnings on users faces for some reason, I believe it's not a good practice to interfere on them in that way. We'd have to cherry pick block some of them or all notices that did not come from UpStream, i.e. Either way, I think we shouldn't touch anything that goes beyond our own scope, at least for now.

imho, these global notices/warnings should be use only for critical motives, not for advertising or anything like that. But yeah, that's debatable. 

not sure if there's an official position on this from WordPress thought.

I'll look for more info as well.

**Comment by upstreamplugin** [comment]
OK. Let's leave on the backburner for now
