### ISSUE TITLE
Improve the filters

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#193]
Right now, we have some filters in the admin:

![screen shot 2017-10-15 at 12 19 24 pm](https://user-images.githubusercontent.com/26938537/31586751-31bab4da-b1a3-11e7-9391-88771dc2888c.png)

Right now, they have some problems:

1) At the bottom of each area, rather than the top. This is not normal WordPress-style, and filters aren't much use if they can't be easily found

2) They don't appear on the frontend

3) Should they be set to hide Completed tasks, by default?

**Comment by upstreamplugin** [comment]
Perhaps we should consider a bulk management option too.

It would be useful to assign 20 / 30 tasks to one user, or to one milestone

**Comment by upstreamplugin** [comment]
Related idea from @awijasa ...

"This is an Upstream frontent feature suggestion.

Just like GitHub's Issue Tracker, what if Open and Closed filters are added to the Task and Bug datatables? If a user clicks Open, the datatable will only show None, In Progress, and Overdue tasks/bugs. For Closed, just show the Completed and Closed tasks/bugs."

**Comment by deenison** [comment]
Thanks @upstreamplugin 

1) The bulk updates feature seems interesting - I've created an individual issue to tackle it - #201

2) About the `Open` and `Closed` suggestion, we already have that one on our plans - #161

**Comment by upstreamplugin** [comment]
Thanks @deenison On the front end, I'm thinking we could consolidate and improve our current options:

![screen shot 2017-10-24 at 10 50 04 am](https://user-images.githubusercontent.com/26938537/31950276-3c65babc-b8a9-11e7-9066-c055fe1d30af.png)

"All Tasks" and "Assigned to me only" could become filters instead of tabs.

Search, Copy, CSV could be items in the same row as the filters

**Comment by upstreamplugin** [comment]
We have one more request along these lines ...

> As time progresses, If we have many old projects(over hundred).
> Can we *archive* our all related projects?

We can do this using the filters, I'm sure. Anything marked as "Closed" can be hidden by default

**Comment by deenison** [comment]
Relates to #154
