### ISSUE TITLE
Warning when adding a task

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#195]
Warning: strlen() expects parameter 1 to be string, array given in /home/elizxer/public_html/wp-content/plugins/upstream/includes/class-up-project.php on line 396

Warning: Cannot modify header information – headers already sent by (output started at /home/elizxer/public_html/wp-content/plugins/upstream/includes/class-up-project.php:396) in /home/elizxer/public_html/wp-content/plugins/upstream-frontend-edit/includes/class-up-frontend-process.php on line 273

**Comment by deenison** [comment]
This issue will be solved along with #210.
