### ISSUE TITLE
Remove the word "settings" from tabs

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#212]
It's getting a bit long here ...
![screen shot 2017-10-31 at 11 07 00 am](https://user-images.githubusercontent.com/26938537/32231333-adbdbb7e-be2b-11e7-8744-f313ce128127.png)

**Comment by deenison** [comment]
I guess I forgot to link this one 😅 
- - -
Relates to #267 

Fixed on [v1.13.2](https://github.com/upstreamplugin/UpStream/releases/tag/v1.13.2).
