### ISSUE TITLE
Improve the Notes area

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#216]
Feature request

Allow the "Notes" field to tie into the WordPress Editor so that other functions are available including Font Size, Font Color, Font type, Tables, Justification, etc.. based on the editor that is currently in use by the WordPress system (image below)

![screen shot 2017-10-31 at 3 21 04 pm](https://user-images.githubusercontent.com/26938537/32244480-2060496c-be4f-11e7-94dd-542b77db5b43.png)

- Fix "Notes" field to allow for Carriage Returns. Right now all the text that is entered becomes a single run-on sentence with word wrap once saved.

![screen shot 2017-10-31 at 3 21 14 pm](https://user-images.githubusercontent.com/26938537/32244494-269d6f80-be4f-11e7-8117-539531d50cbe.png)

**Comment by upstreamplugin** [comment]
Note ... this is the same customer who asked about adding a table button to the WYSIWYG

**Comment by deenison** [comment]
Thanks! I'm breaking down this into two separated issues so we and users can keep better track of them.

- [Editor improvements - #217](https://github.com/upstreamplugin/UpStream/issues/217)
- [Notes editors losing Carriage Returns - #218](https://github.com/upstreamplugin/UpStream/issues/218)
