### ISSUE TITLE
Editor improvements

### ISSUE THREAD

**Issue by deenison** [upstreamplugin/UpStream#217]
Issue reported and extracted from #216
- - -
Allow the "Notes" field to tie into the WordPress Editor so that other functions are available including Font Size, Font Color, Font type, Tables, Justification, etc.. based on the editor that is currently in use by the WordPress system (image below)

![](https://user-images.githubusercontent.com/26938537/32244480-2060496c-be4f-11e7-94dd-542b77db5b43.png)

**Comment by deenison** [comment]
Initially we used to offer all these features in our editors, but the controls were taking too much space in some areas.
Perhaps add some options to admins configure basically what they want on the editors individually?

**Comment by awijasa** [comment]
Hello @deenison and @upstreamplugin,

You may be able to resolve this problem quickly by referring users who request more TinyMCE functions to https://wordpress.org/plugins/tinymce-advanced/

I tried TinyMCE Advanced and it is indeed able to add those extra functions.

Thanks,

@awijasa

**Comment by tardis221** [comment]
@awijasa,

   The upStream team have created some [documentation ](https://upstreamplugin.com/docs/customize-editor-toolbar-upstream/) as a temporary solution to this request and it does utilize the TinyMCE Advanced plugin. They state at the bottom of the document _"We’re working on a more elegant solution for the future."_ 

   Any suggestions you may have in addition to this would certainly speed up the implementation process.

Thank you @awijasa!

-@tardis221

**Comment by awijasa** [comment]
Hi @tardis221,

Thanks for letting me know about the documentation! If I have the chance to work on this, I'll share my findings back to the Upstream team.

@awijasa

**Comment by upstreamplugin** [comment]
Might be best to revisit this after Gutenberg
