### ISSUE TITLE
Notes editors losing Carriage Returns

### ISSUE THREAD

**Issue by deenison** [upstreamplugin/UpStream#218]
Issue reported and extracted from #216
- - -
`Notes` editors content are becoming a single run-on sentence after save.

![](https://user-images.githubusercontent.com/26938537/32244494-269d6f80-be4f-11e7-8117-539531d50cbe.png)

**Comment by tardis221** [comment]
The editor portion is fixed now (THANK YOU 👍), however the Frontend view still lists everything as a run on sentence (no carriage return) under notes as shown in the original screenshot .

**Comment by tardis221** [comment]
@deenison The editor portion is fixed now (THANK YOU 👍), however the Frontend view still lists everything as a run on sentence (no carriage return) under notes as shown in the original screenshot .

**Comment by deenison** [comment]
Thanks for pointing that out @tardis221, you're right.

I'll move this to another issue then. It should be fixed on the next release.
