### ISSUE TITLE
Add any users to a project, not just users in UpStream roles

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#222]
A lot of users are asking for more flexibility on assigning team members to project.

How about if we treated UpStream users just like Client users ... there's a checkbox where you can decide who is assigned to a project?

Basically, we need more clarity on who has access to each project.

**Comment by upstreamplugin** [comment]
@deenison One more reason to do this .... UpStream team members aren't shown as being assigned to a project (their avatar doesn't show, they don't have access) until they've been assigned a project.

I can image a "Team Members" metabox just like this, or perhaps with a multi-select box like we're using for frontend filters:
![screen shot 2018-02-02 at 2 40 57 pm](https://user-images.githubusercontent.com/26938537/35751617-33fdaccc-0827-11e8-9ecb-897482704532.png)

**Comment by upstreamplugin** [comment]
A related point to this ... not every Administrator needs to appear on every project

> I really need a selective choice in Members Role regarding "administrators", whereby an administrator can "Don't show in projects" might be ticked (enabled). Only way for now seems to be fully disable "Projects" in the Members Role setup. Otherwise administrators show up in "All Projects" in frontend.

**Comment by deenison** [comment]
100% agreed, that would add much more flexibility to admins.

A "Team Members" metabox seems like a good approach.

**Comment by stevejburge** [comment]
One more request for this:

> the problem is that UpStream Users can see projects only if an item has been assigned to them in that project. Some users have nothing assigned… but need visibility.

**Comment by stevejburge** [comment]
One more:

"Setting up people on new projects isn't just a simple "Add person to project y", it's hidden under "oh, I have to give them a task in said project and they get auto-added"; NOBODY would intuit this."

**Comment by stevejburge** [comment]
From another customer ...

"whoever created the project is forever linked to that project as the owner and appears in the avatar lists as the owner and as a member. 

The concept of ‘member’ is confused. It appears to merge anyone who is either a client user or project manager or the owner. So the project list which include columns for both users and member is repeating some of those entries in both places. Similarly on the project details page - the members display replicates names that are in other blocks."

Essentially, everyone involved with the project should be added or removed via a checkbox.

**Comment by stevejburge** [comment]
Solved in the next UpStream release
