### ISSUE TITLE
Can't delete discussions in the admin area

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#237]
Not sure if this will be irrelevant when we launch the new comments feature, but the "Delete" button doesn't work for discussions in the admin area
![screen shot 2017-11-21 at 5 22 33 am](https://user-images.githubusercontent.com/26938537/33067416-17f84f44-ce7c-11e7-9697-501a15011054.png)

**Comment by deenison** [comment]
Marking as solved on [v1.13.0](https://github.com/upstreamplugin/UpStream/releases/tag/v1.13.0)
