### ISSUE TITLE
Authors / Editors cannot edit WP posts

### ISSUE THREAD

**Issue by tardis221** [upstreamplugin/UpStream#245]
Authors and Editors (WP Roles) are no longer able to edit Posts. The problem does not occur when role is 'Administrator'. This problem has been occurring since version 1.12.1 (first version I installed of upStream). Sorry it took so long to get to the bottom of it, but here are the details:

**Scenario 1:**
A user account with role assignment of 'Author' in WP attempts to edit their own post. The edit link points to http://_URL_/wp-admin/post.php?post=4558&action=edit but redirects to you http://_URL_/wp-admin/edit.php?post_type=project along with the error "Cheatin’ uh? - Sorry, you are not allowed to edit posts in this post type."
![cheatin huh](https://user-images.githubusercontent.com/7571875/33490674-f224486a-d685-11e7-8d99-30f7ea662ba1.JPG)

**Scenario 2:**
A user account with role assignment of 'Author' in WP along with 'UpStream User' attempts to edit their own post. The edit link points to http://_URL_/wp-admin/post.php?post=4558&action=edit but redirects to you http://_URL_/wp-admin/edit.php?post_type=project# 
![upstream_post_edit_redirect](https://user-images.githubusercontent.com/7571875/33490813-4d72c516-d686-11e7-8a52-825e5dbb5fa8.PNG)

Troubleshooting:

- Reverted theme to standard WP theme and disabled all plugins.
- Post editing worked fine.
- Enabled only the upStream plugin and tested editing again.
- Began receiving the error again. 

It would appear that the post types (Post vs. Project) are being crossed!

Is there a temporary workaround I could try in the meantime? Changing all of my users to 'Administrator' is not an option.

Thank You,
Matthew L

**Comment by awijasa** [comment]
Hello @tardis221,

My workaround for this issue involves modifying the Upstream plugin:

In /upstream/includes/admin/class-up-admin.php, replace:

`if (!in_array($user->ID, $projectMembersList[0])) {`

with:

`if( !in_array( $user->ID, $projectMembersList[0] ) && get_post_type( ( int )$_GET['post'] ) == 'project' ) {`

Then, in /upstream/includes/admin/class-up-admin-project-columns.php within `function filter( $query )`, replace:

`$type = 'project';`

with:

`$type = 'post';`

Please let me know if you have any question.

Thanks,

@awijasa

**Comment by tardis221** [comment]
@awijasa 
   
   Thank you for this. The code changes you suggested fixed the problem immediately. Is there any chance that this will be added into a future update?

**Comment by upstreamplugin** [comment]
Many thanks for reporting this @tardis221 and for the code suggestion @awijasa. Looks like we need to put out a patch release in the next few days.

**Comment by awijasa** [comment]
You're welcome @tardis221 and @upstreamplugin! Also I want to say that the new Upstream comment feature is wonderful!!

**Comment by upstreamplugin** [comment]
That's great to hear, thanks @awijasa. I plan on creating some better documentation for the comments this week. 

We launched comments just before going to WordCamp US, so that got in the way. I'll write more guides on how to use the comments.

**Comment by awijasa** [comment]
Have a great time in WordCamp! I can't make it there, but if I can get there in the future, we should all get together for coffee or something.

I'm looking forward to see the guide on comments later once you have the chance to write it.

**Comment by awijasa** [comment]
Hello @deenison,

I am an AnsPress plugin user, and I just found that the New Question link: /wp-admin/post-new.php?post_type=question would be redirected to /wp-admin/edit.php?post_type=project for an Upstream User.

To fix, `get_post_type( ( int )$_GET['post'] ) == 'project' &&` can be added before `$pagenow === 'post-new.php'` in /upstream/includes/admin/class-up-admin.php.

Thanks in advance!!

@awijasa
