### ISSUE TITLE
Empty Details for Milestones, Tasks, Bug, Files

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#251]
We show the label for "Notes", "Comments" etc, even why there are empty and not useful:

![screen shot 2017-12-07 at 4 00 07 pm](https://user-images.githubusercontent.com/26938537/33738644-e034c080-db67-11e7-9855-a79ceb5a0a4b.png)
![screen shot 2017-12-07 at 4 00 35 pm](https://user-images.githubusercontent.com/26938537/33738645-e048c8d2-db67-11e7-9414-12d213b1d438.png)
![screen shot 2017-12-07 at 4 00 48 pm](https://user-images.githubusercontent.com/26938537/33738646-e05b9926-db67-11e7-9444-353550b2ba2f.png)

**Comment by deenison** [comment]
Not sure if hide those empty columns would be the best approach. Maybe a _none_ text indicating no data?

**Comment by upstreamplugin** [comment]
Yes, we can do "None". 

Alternatively, we could remove this slidedown area entirely and just use the modal.
