### ISSUE TITLE
Administrators may not show up on the Comments area if AAM is installed

### ISSUE THREAD

**Issue by awijasa** [upstreamplugin/UpStream#265]
Hello,

Administrators may not show up on the Comments area if [AAM](https://wordpress.org/plugins/advanced-access-manager/) is installed

![aam exclude administrators from get_users by default](https://user-images.githubusercontent.com/1524802/34264975-35e19b66-e63a-11e7-843b-86100f39a0ff.png)

Workaround:

1. Open /wp-admin > AAM.
2. Click Settings on the AAM configuration page.
3. Disable Backend Access Control.

Thanks,

@awijasa

**Comment by upstreamplugin** [comment]
Thanks @awijasa I wonder if this is something for UpStream's documentation rather than a code fix?

**Comment by awijasa** [comment]
I agree, this should be added to Upstream's documentation.

**Comment by upstreamplugin** [comment]
Thanks @awijasa. I'll close this and write the documentation on the UpStream site

**Comment by upstreamplugin** [comment]
Thanks @awijasa https://upstreamplugin.com/docs/upstream-advanced-access-manager-plugin/
