### ISSUE TITLE
When a comment is added, the assignees, creators, owners, and authors do not receive any email notification

### ISSUE THREAD

**Issue by awijasa** [upstreamplugin/UpStream#266]
Hello,

Users need to be notified via email whenever there is a new comment on Upstream. Otherwise, they won't realize that there is a new comment.

For comment reply notifications, you can simply install [Comment Reply Email Notification](https://wordpress.org/plugins/comment-reply-email-notification/).

I can't find any plugin that is able to provide email notifications for new and approved Upstream comments.

Workaround:

On /upstream/includes/class-up-comments.php, add this line :`wp_new_comment_notify_postauthor( $comment->id );` right above `} catch (\Exception $e) {` in `storeComment` and `approveComment`.

Then, add the code below into the child theme's functions.php:

```
add_filter( 'comment_notification_recipients', 'my_comment_notification_recipients', 10, 2 );

function my_comment_notification_recipients( $emails, $comment_id ) {

    $project = new Upstream_Project( get_comment( $comment_id )->comment_post_ID );

    if( $project ) {

        $project_item_type = get_comment_meta( $comment_id, 'type', true );

        if( $project_item_type == 'project' ) {

            $owner_id = $project->get_meta( 'owner' );

            if( !empty( $owner_id ) ) {

                $owner = get_user_by( 'id', $owner_id );

                if( $owner ) {
                    $owner_email = $owner->get( 'user_email' );
                }

                if( !empty( $owner_email ) ) {

                    $emails = array();
                    $emails[] = $owner_email;
                }
            }
        }
        else {
            $project_item = $project->get_item_by_id( get_comment_meta( $comment_id, 'id', true ), $project_item_type . 's' );

            if( empty( $project_item['assigned_to'] ) ) {

                $creator = get_user_by( 'id', $project_item['created_by'] );

                if( $creator ) {
                    $creator_email = $creator->get( 'user_email' );
                }

                if( !empty( $creator_email ) ) {

                    $emails = array();
                    $emails[] = $creator_email;
                }
            }
            else {
                $assignee = get_user_by( 'id', $project_item['assigned_to'] );

                if( $assignee ) {
                    $assignee_email = $assignee->get( 'user_email' );
                }

                if( empty( $assignee_email ) ) {

                    $creator = get_user_by( 'id', $project_item['created_by'] );

                    if( $creator ) {
                        $creator_email = $creator->get( 'user_email' );
                    }

                    if( !empty( $creator_email ) ) {
                        
                        $emails = array();
                        $emails[] = $creator_email;
                    }
                }
                else {
                    $emails = array();
                    $emails[] = $assignee_email;
                }
            }
        }
    }

    return $emails;
}
```

The code above will send a comment email notification to an Assignee (1st priority), Creator, Project Owner, or Project Author (last ditch attempt).

Thanks,

@awijasa

**Comment by upstreamplugin** [comment]
@awijasa Many thanks

@deenison I like this approach. The simplest approach is probably to email *everyone* on a project when a comment is added.

**Comment by awijasa** [comment]
Hello @upstreamplugin and @deenison,

Ideally, it would be nice to allow the commenter to choose who should get notified. We should also check some options by default.

For a Project Discussion, a commenter shall be able to pick one or more to notify from this hypothetical list of Display Names and UpStream roles + project roles:
[x] upstreamplugin (Project Owner) - default
[ ] deenison (Project Creator)
[ ] emusk (Project Client)
[ ] stevejburge (Administrator)
[ ] awijasa (UpStream Manager)
[ ] whgates (UpStream User)

If a Project Owner is not set, the default will be Project Creator.

For a Milestone/Task/Issue/File (for the example below, I'll generalize this as Task), a commenter shall be able to pick one or more to notify from this hypothetical list of Display Names and UpStream roles + project roles:
[x] deenison (Task Assignee, Project Creator) - default
[ ] upstreamplugin (Task Creator, Project Owner)
[ ] emusk (Project Client)
[ ] stevejburge (Administrator)
[ ] awijasa (UpStream Manager)
[ ] whgates (UpStream User)

If a Task Assignee is not set, the default will be the Task Creator.

Please let me know what you think.

Thanks,

@awijasa

**Comment by upstreamplugin** [comment]
@awijasa I wonder how that would scale? We have some UpStream users who have hundreds of people on a project.

Maybe we can make "Notify everyone on the project" the default? Then a second box "Choose who is notified" with something like your suggestion

**Comment by awijasa** [comment]
Hi @upstreamplugin,

Sounds like a good idea! Knowing now that there are some users who have hundreds project team members, I updated my suggestion above to include categorizations of notifiable users.

Thanks,

@awijasa

**Comment by upstreamplugin** [comment]
Thanks @awijasa. Yes, one of things that's surprised me with UpStream is the scale of some people's projects. 100s of users, 100 of projects.

**Comment by awijasa** [comment]
That's somewhat a good news! :)

**Comment by deenison** [comment]
Liked the idea of choosing who gets notified ad hoc with default options, makes the most sense. In a 100s users scenario, receiving notifications every time one of them leave a comment may be very annoying
