### ISSUE TITLE
Not able to use BuddyPress avatars

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#28]
BuddyPress has a slightly different way of handling avatars.

Can we adjust UpStream to accept BuddyPress avatars?

**Comment by deenison** [comment]
Thanks @stevejburge 
You mean like UpStream should handle user avatars more dynamically as BuddyPress does instead of just trying to retrieve it from Gravatar?

**Comment by stevejburge** [comment]
Yes, one customer in particular runs his whole site through BuddyPress. Upstream couldn't find his avatars.
