### ISSUE TITLE
Project not updating

### ISSUE THREAD

**Issue by Aviorleking** [upstreamplugin/UpStream#280]
OS : Windows 10 x64
Browser : Firefox 57.0.3 x64, Chrome 63.0.3239.84 x64, Chrome 63.0.3239.108 x64
Plugin : 1.13.4
PHP : 5.6
Wordpress : 4.9.1

Observed Behavior :
While trying to update project and pushing 
![image](https://user-images.githubusercontent.com/15822031/34469945-166cb4ea-ef28-11e7-9622-9f642f77b84e.png)
the project don't update and show
![image](https://user-images.githubusercontent.com/15822031/34469955-33278286-ef28-11e7-8d73-0892f146b372.png)
(Tried with only Upstream activated)

Excepted Behavior :
Update the project

**Comment by upstreamplugin** [comment]
Hi @Aviorleking Sorry, we can't provide support here. Can you email help@upstreamplugin.com, please?

**Comment by deenison** [comment]
Thanks @Aviorleking 

Could you be a bit more specific? I'm assuming you're editing from the admin, right?
About the issue, I mean, what information you're trying to update, ie it is some task's titile or a file description or a project owner, etc.
Or absolutely no field is updated regardless of where/what?

**Comment by Aviorleking** [comment]
While editing in the Admin i can't update any fields here
![image](https://user-images.githubusercontent.com/15822031/34487391-686c7c6a-efd4-11e7-8ee3-5e219d4f485a.png)
I push update and then 
![image](https://user-images.githubusercontent.com/15822031/34487412-81145aee-efd4-11e7-88d2-6ce8b23e1683.png)
and in front-end project isn't updated

**Comment by upstreamplugin** [comment]
@Aviorleking Could you try this debugging and see what you find, please:
https://upstreamplugin.com/docs/debug-frontend-upstream/

**Comment by Aviorleking** [comment]
![image](https://user-images.githubusercontent.com/15822031/34488221-e280f460-efd7-11e7-9acc-519da91d1fa1.png)

- Moved to post and edited it
- After Update

**Comment by deenison** [comment]
The issue was confirmed and will be moved to our backlog.
Thanks @Aviorleking

**Comment by Aviorleking** [comment]
Your Welcome !
