### ISSUE TITLE
up-client-users-migration.php warning

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#282]
Reported by a user ...

```
[proxy_fcgi:error] [AH01071: Got error

'php on line 69\nPHP message: PHP Warning: Invalid argument supplied for foreach() in

/..../wp-content/plugins/upstream/includes/up-client-users-migration.php on line 69\nPHP message: PHP Warning:
```

**Comment by deenison** [comment]
I was wondering if we still need this migration script to be executed @upstreamplugin?
It's been a while since those big Clients changes.

The execution happens only once and the script is responsible for converting old Client Users to regular users.

**Comment by upstreamplugin** [comment]
No problem - we can remove now

**Comment by upstreamplugin** [comment]
@deenison Another report of this today. Could we get it fixed quickly?

**Comment by deenison** [comment]
Absolutely. Planning a small patch release for later today/tomorrow tops.
