### ISSUE TITLE
Assign task to Milestones

### ISSUE THREAD

**Issue by Aviorleking** [upstreamplugin/UpStream#283]
Title tell everythings...
Allow us to assign tasks to milestones.

**Comment by upstreamplugin** [comment]
Hi @Aviorleking That should be a core feature of UpStream now. It's not working for you?

![screen shot 2018 01 02 at 11 22 23 am](https://user-images.githubusercontent.com/26938537/34490875-471b59de-efaf-11e7-9eb4-cc1ed592ae1d.png)

**Comment by Aviorleking** [comment]
nope i don't see it 
![image](https://user-images.githubusercontent.com/15822031/34490999-08ca42fc-efe2-11e7-8d67-3fe07835c939.png)
using UpStream 1.13.4

**Comment by Aviorleking** [comment]
Got it now sorry I diasabled Milestones
