### ISSUE TITLE
Add labels/tags to Bugs/Tasks

### ISSUE THREAD

**Issue by Aviorleking** [upstreamplugin/UpStream#284]
add a label/tags for bugs and tasks for categorization (don't know if a spell it correctly) like GitHub or GitLab

PS : Sorry i add a lot of issues for you ;-)

**Comment by upstreamplugin** [comment]
No worries @Aviorleking. Please keep them coming!

This tags feature is underway already. We're going to solve it with the "Custom Fields" extension that launches this week
