### ISSUE TITLE
Add a "Disable Discussion" and "Disable Project Overview" option

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#308]
We've got everything else except "Disable Discussion" and "Disable Project Overview"

![screen shot 2018-01-17 at 10 03 04 am](https://user-images.githubusercontent.com/26938537/35049369-c6d0dfea-fb6d-11e7-8bcf-71f0d76e1ed5.png)

**Comment by deenison** [comment]
It seems that we do have the `Disable Discussion` option. Perhaps changing the texts to `Disable Discussion on <section>`? @upstreamplugin 

![disable-options](https://user-images.githubusercontent.com/1078316/35423457-f5d4aa06-0234-11e8-9a21-dbb458f548b2.png)

Thumbs up for the `Disable Project Overview`.

**Comment by upstreamplugin** [comment]
Sounds good to me @deenison 

We got this request from a user too:

> Regarding your upcoming update it would be very useful if you have time to include a disable feature for your Calendar View extension on Projects - and as a supplement the possibility of Collapsing the element on Projects. Similar to the feature for Tasks, Bugs, Files etc. 

It would make sense to move all of these "Disable" features to a single metabox in the right sidebar.

**Comment by deenison** [comment]
Yes, something like that would be better than we have right now. We have a lot of misplaced options though. 
The settings page demands some handy work and offer a better UX.

**Comment by upstreamplugin** [comment]
Thanks. Thinking this over, a metabox in the right sidebar would be ideal, please. 

At the moment, all the "Disable" boxes get lost. They're all individually hidden inside each different area.

**Comment by deenison** [comment]
Unfortunately the current structure doesn't seem to allow an easy/quick/smart way to add a sidebar on our settings pages. 
Can we group some of those options into sections for now?

something like:
![screen shot 2018-01-31 at 1 00 11 pm](https://user-images.githubusercontent.com/1078316/35629813-bd33279e-0686-11e8-9fce-c34d8baa0180.png)
