### ISSUE TITLE
Some problems with translating UpStream

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#328]
This problem is with the Gannt chart:

> where to translate the month names in the Gantt-Calendar View

**Comment by upstreamplugin** [comment]
Also: 

> there's missing several phrases. Eg. "Save", "Cancel" buttons, header texts in "Files" among others

Here's a screenshot
[Screendump - Translation.pdf](https://github.com/upstreamplugin/UpStream/files/1678012/Screendump.-.Translation.pdf)

**Comment by upstreamplugin** [comment]
> Please also check other Project element pop-up windows - eg. the "Edit" phrase in title when editing a Milestone. Furthermore when adding a Task the fields "Assigned to", "Status" and "Milestone" shows "None" and not the translated term for "None". In the pot-file there only terms of "(None)" so maybe the reference is missing?

**Comment by upstreamplugin** [comment]
Also, the Discussion tab

<img width="370" alt="-1" src="https://user-images.githubusercontent.com/26938537/35573885-4fe3bff4-05a6-11e8-997f-5e08670f7b83.png">

**Comment by deenison** [comment]
Was able to confirm some of the reported missing references, although about the `Save`, `Cancel` etc on frontend, the lang references are located in the Frontend Edit package, not in UpStream's.
