### ISSUE TITLE
Notifications for bugs, but not tasks

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#34]
I see the red icon if bugs are assigned to me, but not tasks

![screen shot 2017-05-09 at 6 32 37 pm](https://cloud.githubusercontent.com/assets/3868028/25875524/f6e664a6-34e5-11e7-93e8-3a26a6dde7b5.png)

**Comment by deenison** [comment]
It seems that right now the badge number only accounts for tasks/bugs whose status is set as `In Progress` or `Overdue`

**Comment by upstreamplugin** [comment]
That's OK. Let's leave it like that at the moment then
