### ISSUE TITLE
Hide milestone filter when Milestones are disabled

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#347]
> A minor UX issue I noticed is that even though Milestones are disabled, the Milestone filtering on a Project's Task list is still shown. Since Milestones are disabled, this filtering option should not be shown.

Here's a screenshot:
![screen shot 2018-02-11 at 10 07 47 am](https://user-images.githubusercontent.com/26938537/36074799-70b21aac-0f13-11e8-8a8d-6742504b9876.png)

**Comment by deenison** [comment]
This was fixed on the v1.15.0 soon-to-be released.
