### ISSUE TITLE
/projects/ login process is broken

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#354]
When someone logs in using the /projects/ URL, they aren't redirected successfully

It sends people to /wp-login.php?redirect_to=.... which turns out to be a broken link

**Comment by deenison** [comment]
Sorry, I was unable to reproduce the broken URL after logging in.

As it is right now, the workflow seems to be like this:
- one tries to access a "protected" page
- he gets redirected to the wp-login.php
- if successfully logged in, WP will send him to that "protected" page

**Comment by deenison** [comment]
The fix might be related with #366.
