### ISSUE TITLE
Allow multiple file uploads on Bugs

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#373]
Steps to reproduce:

- Login to demo website in admin view
- Projects -> Bug Reporting
- Click 'Add Bug' button
- Enter Title
- Click 'Add or Upload File' button in 'Attachments' area
- Select file from Media library or upload file
- Click 'Use This File'
- Repeat steps 5-7

Note: previously added file replaced with the new one, application doesn't allow to add more than 1 file. Not very convenient in regards to usability...

**Comment by deenison** [comment]
Closed in favor of Custom Fields extension.
