### ISSUE TITLE
Project Progress only related to Tasks, not Milestones also

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#387]
At the moment, Tasks have completion percentages.

However, they only count towards project progress if they are also attached to a milestone. We don't need them to be attached to a miletone.

**Comment by stevejburge** [comment]
One more user with this problem today.

They disabled Milestones, and now their project progress doesn't work

**Comment by stevejburge** [comment]
One more request for this today:

> The major issue currently preventing me from using the system right now is the inability to set the % completion for a project or a task.
> 
> I’ve turned off use of milestones, which I have read somewhere has that side effect. From what I can see milestones appear to be far to rigid to accommodate the mix of tasks that I will be managing, It might work if they were all say software development tasks that all follow the same process. But it’s unrealistic to expect all tasks or projects will confirm to the same pattern in real life.
> 
> Regardless of the use of milestone (and I did try turning them on briefly for the sake of testing project completion - but it didn't seem to make any difference) - it’s essential to have a way of setting % complete and marking projects as complete to be able to use Upstream in a live situation.
> 
> Consider the reaction if I were to put this in front of of client and show them a list of project with 0% completion. That’s not going to be acceptable!

**Comment by stevejburge** [comment]
@sergeidevstar001 Short version = Project progress should be based only on Tasks (not Milestones)

This is the current situation and it should change: https://upstreamplugin.com/docs/project-progress-calculated-upstream/

**Comment by sergeidevstar001** [comment]
Thanks, I will check the rule in detail and will fix it perfectly.

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
Then is it need progress on milestone?
![image](https://user-images.githubusercontent.com/39214560/59209801-bc51f880-8bde-11e9-97fb-bfc513793438.png)

And please check my screenshot.
![image](https://user-images.githubusercontent.com/39214560/59209847-d2f84f80-8bde-11e9-93ae-c49491e84f19.png)
Project progress should be 30%, right?

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I didn't set milestone on task, sorry.

**Comment by sergeidevstar001** [comment]
Fixed
