### ISSUE TITLE
Move Filters to "Chosen" style

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#396]
Can we move the Filters to a "Chosen" style where you can select multiple options at once?

![screen shot 2018-02-28 at 7 54 29 am](https://user-images.githubusercontent.com/26938537/36788637-b1983366-1c5c-11e8-8a2c-2d2f7ab52933.png)

That would help with archiving. For example, choose all the statuses except "Closed": https://github.com/upstreamplugin/UpStream/issues/236

**Comment by deenison** [comment]
Sorry, not sure I get the idea. Could you please give an example?

Right now any non-date-nor-search filter supports multiple options, if that's the case 
![screen shot 2018-02-28 at 7 59 24 pm](https://user-images.githubusercontent.com/1078316/36817993-f175a652-1cc1-11e8-8c74-b4e56ce8cee2.png)

**Comment by upstreamplugin** [comment]
Sorry - I'm in idiot. I missed this
