### ISSUE TITLE
Date shows incorrectly in frontend

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#4]
Steps to replicate ...

1) Add a task
2) Set a start date and end date
3) Save the task

The dates show like this ...

![screen shot 2017-04-14 at 1 40 49 pm](https://cloud.githubusercontent.com/assets/3868028/25050960/45e2261c-2118-11e7-9a55-f8cc6581fccc.png)
![screen shot 2017-04-14 at 1 42 15 pm](https://cloud.githubusercontent.com/assets/3868028/25050961/45e67de8-2118-11e7-8fb2-fc6ef97fa56d.png)

**Comment by stevejburge** [comment]
The same is true for Bugs ...

![screen shot 2017-04-14 at 1 44 54 pm](https://cloud.githubusercontent.com/assets/3868028/25051017/9277f9de-2118-11e7-9899-aef3207b879d.png)

**Comment by deenison** [comment]
Thanks for the report @stevejburge. 
What version of UpStream were you able to reproduce the issue?

**Comment by upstreamplugin** [comment]
@deenison This is the very latest, fresh off WordPress.org
