### ISSUE TITLE
Avatars for clients

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#40]
Another avatar issue: can we allow avatars for clients (if they're not using Gravatar)

**Comment by deenison** [comment]
You mean like a form on user profile so he might upload his profile picture agnostically from 3rd party services/plugins?

**Comment by upstreamplugin** [comment]
-- Please reply above this line --


Hello Upstreamplugin/upstream,

We received your email request! We'll get back to you inside 24 hours.

Thank you!

Steve and the UpStream team

**Comment by upstreamplugin** [comment]
Yes, the WordPress core only supports Gravatar, which isn't good because most people don't have accounts there. 

Maybe we could pick a plugin and recommend it, like this: 
https://wordpress.org/plugins/wp-user-avatar/
https://wordpress.org/plugins/avatar-manager/

Or, perhaps we could integrate one of those into UpStream.

**Comment by upstreamplugin** [comment]
Solved in 1.9
