### ISSUE TITLE
Discussion comments are not being rendered on the backend and frontend

### ISSUE THREAD

**Issue by awijasa** [upstreamplugin/UpStream#437]
If I add a comment:

![after adding a comment](https://user-images.githubusercontent.com/1524802/38165337-6a7b68a2-34d7-11e8-8853-a93f1eb069d7.png)

Then refresh the browser, I can't find the comment anymore although it was entered into the database.

![after refreshing](https://user-images.githubusercontent.com/1524802/38165342-7ce8f770-34d7-11e8-8ecc-2af600130d3f.png)

**Comment by deenison** [comment]
Also addressed on [commit #31f5a58e903d31a788354ff372653d94bd08ea12](https://github.com/upstreamplugin/UpStream/commit/31f5a58e903d31a788354ff372653d94bd08ea12)
