### ISSUE TITLE
An item on the frontend can not expand if the width of the browser window is less than 767px

### ISSUE THREAD

**Issue by awijasa** [upstreamplugin/UpStream#457]
![screen shot 2018-04-23 at 12 49 22 pm](https://user-images.githubusercontent.com/1524802/39143916-d5d52bea-46f4-11e8-9f75-682635100b6b.png)

Workaround:

Add this CSS:

```
@media (max-width: 767px), all {

	.o-data-table .hidden-xs {
		display: block !important;
	}
}
```

**Comment by deenison** [comment]
Thanks for pointing it out.

But it doesn't make much sense to force `display: block` in elements having a class that is supposed to do the exact opposite thing on small screens :sweat_smile:
In this case we can simply remove the `.hidden-xs` class from them.
