### ISSUE TITLE
Drag-and-drop to change dates in the timeline

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#489]
_From @upstreamplugin on January 23, 2018 12:51_

This seems like a big task, but potentially useful ...

"Timeline shifts can be very hard to manage because every task and milestone needs to be edited manually.

Could the Project Owner move the timeline using drag-and-drop on the Gantt chart? Or a way to shift all timelines to commence on a date. That way we could add typical timelines for Milestones then when we copy and initialize a project from a template all the dates would be shifted."

_Copied from original issue: AllediaWordPress/UpStream-Project-Timeline#28_

**Comment by andergmartins** [comment]
Check how other libraries handle that:

- http://taitems.github.io/jQuery.Gantt/
- https://dhtmlx.com/docs/products/dhtmlxGantt/
- https://oguzhanoya.github.io/jquery-gantt/
- https://developers.google.com/chart/interactive/docs/gallery/ganttchart
- https://github.com/frappe/gantt
- https://jsganttimproved.github.io/jsgantt-improved/
