### ISSUE TITLE
Using front-end add categories to project

### ISSUE THREAD

**Issue by b-trav** [upstreamplugin/UpStream#556]
It seems to me that users can not currently add categories to a project in the front-end. I think this would be a useful feature.

**Comment by stevejburge** [comment]
Agreed, there are a few missing admin features that aren't available on the frontend yet. Related https://github.com/AllediaWordPress/UpStream/issues/558

**Comment by stevejburge** [comment]
One more request for this

**Comment by stevejburge** [comment]
One more request for this

**Comment by stevejburge** [comment]
Solved with custom fields

**Comment by stevejburge** [comment]
Categories are missing from this frontend modal

<img width="625" alt="Screen Shot 2019-06-04 at 1 53 06 PM" src="https://user-images.githubusercontent.com/3868028/58901919-1e3acb80-86d0-11e9-91f5-1840a2fde5d9.png">

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by stevejburge** [comment]
@sergeidevstar001 Was this resolved successfully?

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
Could you tell me what's wrong for me?
I think it works good on dev server. http://cheerful-skimmer.w5.wpsandbox.pro/projects/
Or I may misunderstood about the issue...

**Comment by stevejburge** [comment]
This is issue is just marked "Fixed" 

No link to a PR, or any other information

**Comment by sergeidevstar001** [comment]
When I fix #71 Custom Field Plugin issue, I fixed it too, because it related with custom field plugin

**Comment by stevejburge** [comment]
OK, sorry for the confusion. There is another Categories option. See the right column here:

<img width="1116" alt="Screen Shot 2019-07-16 at 5 37 02 PM" src="https://user-images.githubusercontent.com/3868028/61308334-59acd780-a7f0-11e9-8088-00fe551cb3bd.png">

However, maybe we should encourage people to use Custom Fields instead.

**Comment by stevejburge** [comment]
Closed in favor of https://github.com/upstreamplugin/UpStream/issues/842
