### ISSUE TITLE
Allow admins  to edit email notifications

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#620]
> email notification TEMPLATE editable by admin - I cannot see where the template is atm

**Comment by loftwah** [comment]
The template for this is in the plugin.php file for the Email Notification plugin. The documentation points towards the reminder system but that has no impact on the notification emails.

**Comment by stevejburge** [comment]
Thanks @loftwah I'm going to close this in favor of https://github.com/upstreamplugin/UpStream/issues/612

Plus, we got your support ticket.

We know the notifications need improvement. Our plan is to import that notifications library
