### ISSUE TITLE
Allow people to customize email notifications

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#631]
From a customer:

> email notifications too simple (no graphics and no possibility of customization with logo and other graphic material

**Comment by loftwah** [comment]
How is this going? I need to be able to include the project data in the notification email so users can get the info right from their inbox. How likely is it that this will be coming soon? I could add it myself if I knew which function to run. I tried a couple of different functions but I'm a bit rusty with PHP and it kept breaking the plugin. The end goal is that when a user is assigned a Task from a Project that the information for the task is actually included in the email.

I'm editing the plugin.php file in the email notification plugin and haven't had any success yet.

Cheers
Dean

**Comment by stevejburge** [comment]
Thanks Dean

We got your support ticket so we'll try to answer there and also improve the notifications.

Overall, this our upcoming solution https://github.com/upstreamplugin/UpStream/issues/612
