### ISSUE TITLE
Assign tasks, milestones, files etc to multiple users

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#65]
A user requested the ability to add more than one person to a task

**Comment by upstreamplugin** [comment]
Perhaps this is the right place to add this request ... "assign tasks to client users as well"

This could also be related to #133

**Comment by tardis221** [comment]
@upstreamplugin I too am looking for this functionality.

**Comment by upstreamplugin** [comment]
One more user vote for this

**Comment by upstreamplugin** [comment]
Another vote for this: "Is it possible to have a Task assigned to more than one User. The Task notification would function as a meeting invite in those cases."

**Comment by upstreamplugin** [comment]
More on this: "Regarding adding multiple users for a task, a task might be a meeting. We end up using Go To Meeting or Office to invite attendees, but it would be cool if we could just post the meeting call-in details in a task and send it out. Job Done."

**Comment by upstreamplugin** [comment]
Another vote for this from a customer

**Comment by upstreamplugin** [comment]
Another vote for this cc @deenison 

> Can you add more than one User to each task? I don't see that option, or how to do that other than to repeat the task multiple times, assigning to one person at a time?

**Comment by upstreamplugin** [comment]
As we get ready to launch, hopefully we can solve this issue by including Clients https://github.com/upstreamplugin/UpStream/issues/133

**Comment by deenison** [comment]
Issues #65, #133 and #405 will be shipped all together yes
