### ISSUE TITLE
Make Start Dates and End Dates available as sortable columns

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#671]
> Is there a way to sort projects by their due dates (not just the 
> date they were entered)? I know there are plugins that allow users to 
> reorder posts but I didn't know if this would work with Projects.
> 

It would make sense for Start Dates and End Dates to be in columns here:
![screen shot 2018-11-20 at 1 22 32 pm](https://user-images.githubusercontent.com/3868028/48794243-63188b00-ecc7-11e8-8f24-259e02d13f6e.png)

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
There is only one arrow to sort that can be sorted by project title.
Then do I have to add one arrow too or don't need sort by project title?

**Comment by stevejburge** [comment]
@sergeidevstar001 I thought this might help with the export ... we can literally create new columns

So the column order will be:

Project
Start Date
End Date
Client
Client Users
Project Members 
etc

**Comment by sergeidevstar001** [comment]
I got it, Thanks

**Comment by sergeidevstar001** [comment]
Fixed
