### ISSUE TITLE
Is there any point to keeping project categories?

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#68]
Do we use Project Categories anywhere in the code? Can we think of any reason to keep them?

**Comment by deenison** [comment]
Theoretically this might be useful if an admin has a lot of projects of different natures, but it doesn't seem we are using/displaying that categorization anywhere but the form.

Should we remove this feature from Projects? @upstreamplugin

**Comment by upstreamplugin** [comment]
Maybe just comment it out for now?

**Comment by deenison** [comment]
Agreed, in case we need we need that back in the future.

**Comment by deenison** [comment]
What about keeping that but as an optional feature? Perhaps disabled by default.

**Comment by upstreamplugin** [comment]
Yes, that works
