### ISSUE TITLE
The calendar resets after moving an item after using date navigation

### ISSUE THREAD

**Issue by andergmartins** [upstreamplugin/UpStream#681]
Use the arrows to navigate to another date in the calendar. Find an item and move it to another date.
It will work, but the calendar will reset forgetting the current date you navigated to.

Related to #525.

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
When you have some spare time, could you share screenshot for this issue?
I can't find the issue on front-end, sorry.

**Comment by andergmartins** [comment]
You are right, I think this is not an issue anymore. I wasn't able to reproduce it again. We probably fixed it in a previous release. I'm closing it. Tks.
