### ISSUE TITLE
When there is no project, opening /projects (frontend) will cause the user to see nothing or the default archive page

### ISSUE THREAD

**Issue by awijasa** [upstreamplugin/UpStream#699]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

I expect to see an empty Project list page with a note: "It seems that you're not participating in any project right now."

## Current Behavior

The /projects page will say "Nothing Found" instead, or it would load the default archive page.

## Possible Solution

Check if the current page's URL path is on /projects. If that's the case, make sure that UpStream's frontent archive page template is loaded. Also make sure that the frontend styles and JS scripts are loaded.

## Steps to Reproduce (for bugs)

1. Delete all the projects
2. Open .../projects
3.
4.

## Context

 User experience issue. Assuming UpStream Frontend Edit is installed, a user could have create a new project by going to /projects, but if he/she can only see "Nothing Found" or a default WordPress archive page, he/she won't be able to do so and would be forced to go to /wp-admin to create a new project.

## Your Environment

* Version used: 1.23.2
* Browser Name and version: Chrome for Mac version 73.0.3683.75 (64-bit)
* Operating System and version (desktop or mobile): macOS Mojave 10.14.3 for desktop
* Link to your project: http://misty-moose.w6.wpsandbox.pro (demo instance)

**Comment by stevejburge** [comment]
Thanks so much for such a detailed report @awijasa. We're going to set aside time this week to go over this and your PRs in detail

**Comment by awijasa** [comment]
Hi Steve,

Thanks for the update! Attached is the screenshot of what I would see on an
UpStream demo instance when all the projects are deleted.

Please let me know if there is anything I can do to help.

Adrian

**Comment by stevejburge** [comment]
Thanks for reporting this @awijasa. One idea would be to load a sample project

**Comment by awijasa** [comment]
Hi @stevejburge,

Thanks for the update! While loading a sample project may solve the problem, if the user then deletes the sample project, he/she may be confused when seeing the 'Nothing Found' page under .../projects

@awijasa

**Comment by stevejburge** [comment]
Good point, thanks @awijasa

**Comment by stevejburge** [comment]
One customer report about this today

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
So you mean... if there is no project, when user is going to go /projects, it need to redirect to create new project page on admin?

**Comment by stevejburge** [comment]
@sergeidevstar001 No, I think the solution is just to prevent the /projects page from breaking

Try deleting all the projects on an UpStream demo site

You will get an empty, default WordPress screen

<img width="970" alt="Screen Shot 2019-06-18 at 8 04 42 AM" src="https://user-images.githubusercontent.com/3868028/59680620-c906bb80-919f-11e9-97f9-bdc97c59c563.png">
