### ISSUE TITLE
Remove option to display bars in the calendar

### ISSUE THREAD

**Issue by andergmartins** [upstreamplugin/UpStream#703]
This feature is probably broken since the drag-and-drop launch.

**Comment by stevejburge** [comment]
I'm OK with removing this, if needed

**Comment by stevejburge** [comment]
Let's remove this and the bars setting:

<img width="807" alt="Screen Shot 2019-05-20 at 12 24 08 PM" src="https://user-images.githubusercontent.com/3868028/58036913-315b7200-7afa-11e9-81a8-9e181f99c862.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
So you mean... you want to remove Calendar Overview Settings, right?
![image](https://user-images.githubusercontent.com/39214560/59297711-79198780-8cbb-11e9-91f0-3b25f7c5a543.png)

**Comment by stevejburge** [comment]
Yes, we used to offer a "bars" display in the calendar but that's gone now

**Comment by sergeidevstar001** [comment]
I got it, Thanks.

**Comment by sergeidevstar001** [comment]
Fixed.
