### ISSUE TITLE
Sunday tooltips get lost in Calendar

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#713]
- open project URL.                                                                                  
- Add a task so that it will be scheduled to start or finish on Sunday (in order to make it appear in the right most cell).                                                                               
- Click on the task to see its "rollout" tooltip with details.
- The tooltip is not visible fully.

<img width="528" alt="Screen Shot 2019-03-25 at 11 32 34 AM" src="https://user-images.githubusercontent.com/3868028/54932769-ccb4da00-4ef1-11e9-96bb-cc2b024ef7fb.png">

**Comment by andergmartins** [comment]
I can't reproduce this anymore. Let try again with the new beta

**Comment by stevejburge** [comment]
Solved in 1.24.0
