### ISSUE TITLE
Sorting by progress is incorrect

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#716]
This image shows sorting by Progress: the ordering is wrong

<img width="858" alt="Screen Shot 2019-03-25 at 11 47 16 AM" src="https://user-images.githubusercontent.com/3868028/54933862-d8a19b80-4ef3-11e9-83fa-2f4903aac58e.png">

**Comment by sergeidevstar001** [comment]
Fixed.
