### ISSUE TITLE
Tinymce external plugins for working on UpStream pages

### ISSUE THREAD

**Issue by andergmartins** [upstreamplugin/UpStream#717]
We added a few filters for allowing customize tinymce, but external plugins added there are not working.

**Comment by andergmartins** [comment]
Added a new filter for external plugins on 456ef3724eb0bd4327a97d5d784622e7b8ad0181, but that seems to not work very well on the project admin page. It shows a lot of 404 errors.

<img width="1274" alt="Screen Shot 2019-03-25 at 15 45 46" src="https://user-images.githubusercontent.com/407131/54945632-1367fb80-4f15-11e9-81f5-e57c68697069.png">

**Comment by andergmartins** [comment]
Related to this support ticket https://secure.helpscout.net/conversation/801688420/90180?folderId=2558672 (Private)

**Comment by stevejburge** [comment]
Solved in 1.24.0
