### ISSUE TITLE
Can't publish a MIlestone

### ISSUE THREAD

**Issue by andergmartins** [upstreamplugin/UpStream#726]
The Milestone Button is disabled and we have some JS errors:

Uncaught TypeError: $(...).datepicker is not a function
wp-auth-check.min.js?ver=5.1.1:1 Uncaught TypeError: Cannot read property 'hasClass' of undefined

**Comment by andergmartins** [comment]
After fixing, answer here: https://secure.helpscout.net/conversation/738023010/83099?folderId=2558672

**Comment by stevejburge** [comment]
Solved in 1.24.0
