### ISSUE TITLE
Remove user groups on uninstall

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#74]
Can we remove the two UpStream user groups when someone uninstalls?

**Comment by upstreamplugin** [comment]
Looks like everything else is removed if you check "Remove all data on uninstall?"

**Comment by deenison** [comment]
Yes, you're right. Everything is removed if the `Remove all data on uninstall` option is checked.

I think the label "uninstall" can be a bit misleading here. Should this clean up be executed once the plugin is deactivated or deleted from the WP instance?

We could perhaps remove the roles right on deactivation, so users stop seeing them for no reason. Current users within these roles would be left without none, but if the plugin happens to be reactivated they would be assigned back to what they were.

**Comment by upstreamplugin** [comment]
I'd say remove the roles if this box is checked ... "Remove all data on uninstall?"
