### ISSUE TITLE
Client Filters doesn't accept spaces

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#740]
It's not possible to type two words into the "Clients" filter on the main "Projects" page
<img width="1110" alt="Screen Shot 2019-04-18 at 4 05 38 PM" src="https://user-images.githubusercontent.com/3868028/56388076-1395a700-61f4-11e9-8bb2-d470c76d7ae0.png">

**Comment by sergeidevstar001** [comment]
Fixed
