### ISSUE TITLE
Discussions box appears on Milestones screen

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#745]
When you first access Milestones, the Discussion box appears:
<img width="912" alt="Screen Shot 2019-04-30 at 11 51 21 AM" src="https://user-images.githubusercontent.com/3868028/56975237-5c2b5980-6b3e-11e9-8862-7a4eaaca9200.png">

Remove it and you get a blank area:

![Screen Shot 2019 04 30 at 11 50 51 AM](https://user-images.githubusercontent.com/3868028/56975243-60f00d80-6b3e-11e9-8bc8-edd27a7ea6d4.png)

**Comment by sergeidevstar001** [comment]
![image](https://user-images.githubusercontent.com/39214560/58280069-6f92b300-7dd2-11e9-9f75-bc8bc8511fdc.png)
![image](https://user-images.githubusercontent.com/39214560/58280188-9cdf6100-7dd2-11e9-86ca-145e94e727b8.png)

**Comment by stevejburge** [comment]
@sergeidevstar001 true, but we're thinking of new users who might not be familiar with WordPress

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I think all users are familiar with basic wordpress technology whom are going to use the plugin.
Thanks.

**Comment by stevejburge** [comment]
@sergeidevstar001 We do get a lot of beginners. This is worth fixing

**Comment by sergeidevstar001** [comment]
Then I will try to fix it by using style.

**Comment by sergeidevstar001** [comment]
Fixed :)
