### ISSUE TITLE
Arrows missing from milestone date popup

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#746]
<img width="412" alt="Screen Shot 2019-04-30 at 11 52 26 AM" src="https://user-images.githubusercontent.com/3868028/56975310-89780780-6b3e-11e9-8e69-ebe6bd68e42b.png">

**Comment by sergeidevstar001** [comment]
[datepicker.zip](https://github.com/upstreamplugin/UpStream/files/3205598/datepicker.zip)

Please copy it and paste to plugin directory / includes / admin / assets / img / 

Then it will resolved
