### ISSUE TITLE
Possible to enter invalid dates in milestone calendar

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#747]
<img width="450" alt="Screen Shot 2019-04-30 at 11 52 48 AM" src="https://user-images.githubusercontent.com/3868028/56975328-9563c980-6b3e-11e9-8231-bb47d9ecf6f1.png">

**Comment by sergeidevstar001** [comment]
plugins / upstream / includes / admin / asserts / js / admin.js -> line 158
You can find $('.o-datepicker').datepicker({ ....
Before it, please add some js code
$("#_upstream_milestone_start_date").datepicker({
        numberOfMonths: 2,
        dateFormat: 'yy-mm-dd',
        onSelect: function(selected) {
          $("#_upstream_milestone_end_date").datepicker("option","minDate", selected)
        }
    });
    $("#_upstream_milestone_end_date").datepicker({
        numberOfMonths: 2,
        dateFormat: 'yy-mm-dd',
        onSelect: function(selected) {
           $("#_upstream_milestone_start_date").datepicker("option","maxDate", selected)
        }
    }); 
Then it will be resolved. :)
