### ISSUE TITLE
Can't add reminders in the milestone screen

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#748]
Pop-up box won't work:

<img width="724" alt="Screen Shot 2019-04-30 at 11 54 30 AM" src="https://user-images.githubusercontent.com/3868028/56975433-d2c85700-6b3e-11e9-88a4-11a5a6be7a3e.png">

Error message:
<img width="367" alt="Screen Shot 2019-04-30 at 11 55 08 AM" src="https://user-images.githubusercontent.com/3868028/56975436-d52ab100-6b3e-11e9-9e74-8220c07bfb1a.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I'm sorry, I can't find the screen on plugin page.
Will wait for your help.

**Comment by sergeidevstar001** [comment]
Now it will be work, because there is the file on include / admin / assets / img / datepicker / ui-icons_222222_256x240.png

**Comment by stevejburge** [comment]
Thanks

**Comment by stevejburge** [comment]
@sergeidevstar001 Did this get committed?

**Comment by sergeidevstar001** [comment]
![image](https://user-images.githubusercontent.com/39214560/58898594-7bb13580-872d-11e9-8282-037fcc78eb83.png)
The button works now.
