### ISSUE TITLE
Missing the Start and End arrows for Milestones

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#749]
We have start and end arrows for Tasks, but not Milestones
<img width="678" alt="Screen Shot 2019-04-30 at 11 57 12 AM" src="https://user-images.githubusercontent.com/3868028/56975591-233fb480-6b3f-11e9-947b-ce6d8fde93c4.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
It have to display only task, right?
Currently it shows milestones too.

**Comment by stevejburge** [comment]
@sergeidevstar001 It should show both Milestones and Tasks

**Comment by sergeidevstar001** [comment]
I got it, Will check current problem in detail.
Thanks.

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I'm sorry, I don't understand what's issue on #749
Could you tell me what's problem for me?

**Comment by stevejburge** [comment]
Each Task and Milestone has a start date and an end date

Start date arrows point to the right
End date arrows point to the left

This screenshot has better examples. Those are all End dates

<img width="993" alt="Screen Shot 2019-05-30 at 1 46 08 PM" src="https://user-images.githubusercontent.com/3868028/58652345-56619900-82e1-11e9-8998-94b30f887d5e.png">

**Comment by sergeidevstar001** [comment]
Thanks.

**Comment by sergeidevstar001** [comment]
![image](https://user-images.githubusercontent.com/39214560/58654694-1931f100-834b-11e9-890d-666ddf16e0c5.png)
![image](https://user-images.githubusercontent.com/39214560/58654756-3c5ca080-834b-11e9-9c26-63e7c6da1de1.png)
Now I can't update source (UpStream-Calendar-View).
And you can see start date by using back button.
When title text size is long, the arrow didn't show, so I fixed it.

**Comment by stevejburge** [comment]
@sergeidevstar001 Check your access again now

**Comment by sergeidevstar001** [comment]
It works, Thanks. (Fixed)
