### ISSUE TITLE
CSS and JS loading on too many admin pages

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#751]
This is the source code on the main WordPress dashboard, for example. We should only load UpStream assets on UpStream pages

<img width="1209" alt="Screen Shot 2019-04-30 at 12 09 59 PM" src="https://user-images.githubusercontent.com/3868028/56976428-ec6a9e00-6b40-11e9-832d-6c5afad0e12b.png">

**Comment by sergeidevstar001** [comment]
plugins / upstream / include / frontend / up-enqueuqes.php -> line 14 
You can find upstream_enqueue_styles_scripts() function
Before line 54 -> wp_enqueue_style() function, need to write if condition.
if(!is_admin) {}
Then it will not load on admin dashboard.
