### ISSUE TITLE
UpStream breaks on multisite

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#762]
**See the attached screenshots. I noticed the javascript_error when I tried to view the manager, but did not see anything similar when trying to add a project.
[Attachments.zip](https://github.com/upstreamplugin/UpStream/files/3143030/Attachments.zip)
*

**Comment by stevejburge** [comment]
Message: 
`The plugin generated 9159 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.`

![Screen Shot 2019-05-03 at 1 57 26 PM](https://user-images.githubusercontent.com/3868028/57156214-68681e80-6dab-11e9-9dbb-3168298aa3a6.png)

**Comment by sergeidevstar001** [comment]
Fixed
