### ISSUE TITLE
Delete button on frontend for Projects

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#763]
A user has requested a "Delete" button for projects on the frontend.

We have it for Tasks, Bugs etc already. 

We can add a red delete button to the bottom-left corner here:
<img width="662" alt="Screen Shot 2019-05-03 at 3 28 35 PM" src="https://user-images.githubusercontent.com/3868028/57160912-272a3b80-6db8-11e9-9b56-ed84b0686170.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I fixed it, but I can't update the code, because I have no access to update the git repository.
![image](https://user-images.githubusercontent.com/39214560/58312865-ca61f400-7e3e-11e9-9110-82a359990b24.png)
Repository name : upstreamplugin/UpStream-Frontend-Edit

**Comment by stevejburge** [comment]
@sergeidevstar001 Any better now?

**Comment by sergeidevstar001** [comment]
Thanks, I can commit now.
#763 issue : fixed.
And could you check my message on upwork for me?

**Comment by sergeidevstar001** [comment]
Fixed it.
