### ISSUE TITLE
Project Overview data is all 0 when project is a draft. It only calculates for published projects

### ISSUE THREAD

**Issue by andergmartins** [upstreamplugin/UpStream#764]
After copying a project the new one is created with as a draft. The summary is all zero. Publish it and the summary will update.

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
Could you provide screenshot for the issue for me?

**Comment by andergmartins** [comment]
Hi @sergeidevstar001 I'm reviewing this issue. I changed the title a little bit. When you change the project status to Draft, all the numbers become 0 (copied or not). If you publish it updates. 

Here is the overview for a published project:

<img width="1138" alt="Screen Shot 2019-06-11 at 17 36 16" src="https://user-images.githubusercontent.com/407131/59304880-73965000-8c6f-11e9-8e49-1b8859e89c33.png">

Here is the overview when the same project is a draft:
<img width="1081" alt="Screen Shot 2019-06-11 at 17 36 59" src="https://user-images.githubusercontent.com/407131/59304929-8c9f0100-8c6f-11e9-91d9-9b2ab084d038.png">

**Comment by sergeidevstar001** [comment]
Thanks, will fix it

**Comment by sergeidevstar001** [comment]
Fixed
