### ISSUE TITLE
Milestones not reordering correctly

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#772]
> When I create a new project, or when I try to update the project templates, the milestones are not saving in the correct order in the backend. Even after I reorder them, they aren't saving in the right order. Top = the order it should be saving. Bottom = order in which it is actually saving.

![Screen-Shot-2019-05-09-at-2-15-40-PM](https://user-images.githubusercontent.com/3868028/57529017-d8bdf500-7301-11e9-808c-07aea11c4899.png)

**Comment by sergeidevstar001** [comment]
Problem : includes / frontend / up-table-functions.php -> line 19
getMilestonesFields() {
$schema = [
        'milestone'   => [
            'type'        => 'raw',
            'isOrderable' => true,
            'label'       => upstream_milestone_label(),
}
The code doesn't work.

**Comment by stevejburge** [comment]
Thanks @sergeidevstar001 We just made a change to the way that Milestones work. That was in version 1.24 - the most recent update

**Comment by sergeidevstar001** [comment]
Great

**Comment by stevejburge** [comment]
Sure thing. Quite a lot of these new issues are releated to this Milestones feature. They are small bugs introduced after the update

**Comment by stevejburge** [comment]
@sergeidevstar001 Sorry. That didn't get it. 

Here are the arrows that aren't working

![Screen Shot 2019 05 22 at 5 10 48 PM](https://user-images.githubusercontent.com/3868028/58209340-e76abb80-7cb4-11e9-8e07-90736dca2a89.png)

**Comment by andergmartins** [comment]
@sergeidevstar001 I think part of the problem is here: 

https://github.com/upstreamplugin/UpStream/blob/development/includes/class-up-milestone.php#L545
https://github.com/upstreamplugin/UpStream/blob/development/includes/admin/class-up-admin-metaboxes.php#L104

and probably in more places. I think the mistake was that I coded that part thinking about alphabetical ordering, like the other columns displayed in the frontend. And probably broke the ordering feature when I converted milestones to posts.

**Comment by sergeidevstar001** [comment]
@andergmartins  I debugged it, currently it related with post id, and set order function saves milestone name, so it's wrong I think.
So it need to add new function to order milestone.

**Comment by stevejburge** [comment]
Thanks @sergeidevstar001 Could you create a PR?

**Comment by sergeidevstar001** [comment]
Hi, Steve.
I will add new field to fix current issue.
Thanks.

**Comment by stevejburge** [comment]
@sergeidevstar001 The arrows are a bad user interface

If there's another option, such as drag-and-drop, that might be better

**Comment by sergeidevstar001** [comment]
I got it.
But it need some time to make the function.

**Comment by andergmartins** [comment]
Hi @sergeidevstar001, the changes you introduced on the commit https://github.com/upstreamplugin/UpStream/commit/1fcd741aa8c7b7798717246ad9d5fa34711f1642 works well for milestones, it is an improvement to UI, for sure. Thanks.

But I think it is very important to keep consistence in the UI, and the changes only addresses Milestones, but Tasks and Bugs still have the old buttons. So I created a new issue https://github.com/upstreamplugin/UpStream/issues/786 for addressing the other project items.
