### ISSUE TITLE
Project Exports feature is missing users

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#783]
UpStream has a CSV export feature:
![export](https://user-images.githubusercontent.com/3868028/58481005-836b4b80-8129-11e9-983f-9c5ad83bd322.png)

When used for "Projects" the "Client Users and "Project Members" columns are empty

<img width="763" alt="Screen Shot 2019-05-28 at 9 18 56 AM" src="https://user-images.githubusercontent.com/3868028/58481068-a3027400-8129-11e9-8641-0bd23a461185.png">

**Comment by sergeidevstar001** [comment]
Problem : Client Users, Project Members have only user icon, but it need text to convert to CSV.
Solution : Add user name on Client Users, Project Members (like img + text)

**Comment by stevejburge** [comment]
@sergeidevstar001 The names should be available. Hover over them:
<img width="562" alt="Screen Shot 2019-05-28 at 11 13 04 AM" src="https://user-images.githubusercontent.com/3868028/58489611-9ab23500-8139-11e9-847a-1c7ec129e20a.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
But it can't read hover text on CSV exporter.
So it need to write the name like screenshot.
![image](https://user-images.githubusercontent.com/39214560/58490274-7426e500-819f-11e9-955f-9165b0acc4c9.png)

**Comment by stevejburge** [comment]
@sergeidevstar001 We could make this more useful thanks to a customer request https://github.com/upstreamplugin/UpStream/issues/785

**Comment by sergeidevstar001** [comment]
Fixed #785 :)
