### ISSUE TITLE
Allow people to show usernames instead of avatars

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#785]
Two customers today have asked if it's possible to show the username instead of the avatar on the frontend of the site.

I think avatars should be the default still, but showing names could be an option

**Comment by sergeidevstar001** [comment]
![image](https://user-images.githubusercontent.com/39214560/58535148-c576b900-821f-11e9-8ac9-5153cea716f5.png)
I'm going to make an option for it.

**Comment by stevejburge** [comment]
Thanks @sergeidevstar001. This could also be a global setting

**Comment by sergeidevstar001** [comment]
![image](https://user-images.githubusercontent.com/39214560/58575364-76a73e80-8274-11e9-9ea8-d992e08d34bf.png)
Fixed it.

**Comment by stevejburge** [comment]
Great, thanks @sergeidevstar001

**Comment by andergmartins** [comment]
@sergeidevstar001 Sorry, 

I see some details to fix. The issue asks to add option to "replace" avatars with the "names", not to "add names". 

This is the result I see when I enable that new option:

<img width="1020" alt="Screen Shot 2019-07-03 at 12 05 08" src="https://user-images.githubusercontent.com/407131/60603035-5c88e080-9d8b-11e9-9229-27520916b05d.png">

This is what I think it should display:

<img width="1024" alt="Screen Shot 2019-07-03 at 12 07 32" src="https://user-images.githubusercontent.com/407131/60603101-79bdaf00-9d8b-11e9-8550-c152ae8c446c.png">

It says to show names "instead" of avatars. 

If we decide to allow showing both, we would need to fix the CSS so it displays inline, and add a third option: Avatars, Avatars + Names, Only Names. 

@stevejburge what do you think?

**Comment by stevejburge** [comment]
@stevejburge @sergeidevstar001 Yes, this should be "names" or "avatars". I don't think there's room for both

**Comment by sergeidevstar001** [comment]
I understand, Thanks

**Comment by sergeidevstar001** [comment]
Fixed
