### ISSUE TITLE
Fix consistency in the way we reorder Milestones and other project items in the admin

### ISSUE THREAD

**Issue by andergmartins** [upstreamplugin/UpStream#786]
The commit https://github.com/upstreamplugin/UpStream/commit/1fcd741aa8c7b7798717246ad9d5fa34711f1642 removed the old buttons and introduced drag-and-drop for reordering Milestones. That works well, but we still have buttons for Tasks, Bugs, and Files.

It is very important to keep consistency on the UI.

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
So you mean... Tasks, Bugs and Files need to update like Milestone reordering too?

**Comment by andergmartins** [comment]
@sergeidevstar001 yes, please. If we reorder milestones using drag-and-drop, it would be intuitive and expected to be allowed to do the same with tasks, bugs and files.

**Comment by sergeidevstar001** [comment]
Fixed :)
