### ISSUE TITLE
Improve Project CSV export by splitting columns

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#787]
At the moment, the CSV export for projects puts the Title, Start Date and End Date into the same column. This should be 3 separate columns.

We can also clean up the "Progress" column which has the progress listed twice
<img width="785" alt="Screen Shot 2019-05-29 at 7 20 37 AM" src="https://user-images.githubusercontent.com/3868028/58553205-52028680-81e2-11e9-850c-fde6e27fed09.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I fixed "Progress" column issue.
But it need to divide columns for 3 separate columns ("Title, Start Date and End Date").
![image](https://user-images.githubusercontent.com/39214560/58570607-dbf63200-826a-11e9-9bd6-0c7e8e9dfd20.png)
Currently it's one column, it's problem.

**Comment by stevejburge** [comment]
@sergeidevstar001 Yes, we may need to make changes elsewhere in UpStream to fix this

**Comment by sergeidevstar001** [comment]
Then you mean... you need to change CSV export library?

**Comment by stevejburge** [comment]
Possibly yes - we'll need to figure out how to split these columns

**Comment by sergeidevstar001** [comment]
Then let's me find solution.

**Comment by sergeidevstar001** [comment]
I debugged it today, so it used Gettext\Generators library.
But it used only fputcsv function (it's php core function), so can't customize it.
I will try to find another solution for you.

**Comment by stevejburge** [comment]
Thanks @sergeidevstar001

**Comment by oraclerob** [comment]
@stevejburge can we please get an update on this one as this bug needs to be fixed by end of month for your customer.

**Comment by stevejburge** [comment]
@oraclerob Sure, we can prioritize this. We appreciate your feedback to help make UpStream better.

We avoid guaranteeing fixes by a certain deadline (things happen) but we'll put this on the front-burner.

**Comment by stevejburge** [comment]
One more customer request for this today. 

@sergeidevstar001 let's prioritize this one

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
Current solution : It need to divide column for it.
I didn't found great solution yet, sorry.

**Comment by stevejburge** [comment]
I think this problem is closely related to https://github.com/upstreamplugin/UpStream/issues/671

**Comment by andergmartins** [comment]
@sergeidevstar001 I was taking a look and I think I have a fix for this one. Please, could you try checking the Pull Request I created for your `fixing` branch? If it works, feel free to merge it into your branch and remove mine 👍

**Comment by sergeidevstar001** [comment]
Fixed by @andergmartins
