### ISSUE TITLE
Copy Project doesn't assign Tasks to Milestones correctly

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#788]
The "Copy Project" extension adds a "Copy" feature to each project
<img width="328" alt="Screen Shot 2019-05-29 at 7 33 35 AM" src="https://user-images.githubusercontent.com/3868028/58553873-149ef880-81e4-11e9-9788-43a3405ed62f.png">

It copies Milestones and Tasks correctly. However, the Milestones lose their connection to Tasks.

You can see the situation on the UpStream demo sites. Click "Copy" for the "Designing A New Website" project. The Project Timeline shows that they are not connected correctly:

<img width="930" alt="Screen Shot 2019-05-29 at 7 34 35 AM" src="https://user-images.githubusercontent.com/3868028/58554038-43b56a00-81e4-11e9-893f-b1561fe284c3.png">

**Comment by sergeidevstar001** [comment]
Problem : when copy project, it clone _upstream_project_tasks, but it includes old milestone id info,
          so it need to replace milestone id with created milestone id on _upstream_project_tasks

**Comment by sergeidevstar001** [comment]
Solution : when clone milestones, it need to save corresponding relation (new milestone : original milestone)
  When clone task, it need to replace old milestone id to new milestone id
But it's a little difficult :)

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
I added newId on milestone to resolve #788 (edited) 
public function getId() { return $this->postId; }
   public function getNewId() { if (!empty($this->newId)) { return $this->newId; }
       $this->newId = $this->getMetadata(self::META_NEW_ID, true);
       return $this->newId;
   }
UpStream / includes / class-up-milestone.php
And when copy milestone on UpStream-Copy-Project / library / plugin.php : Line 520
copyMilestones() function
$milestone->setNewId($milestoneClone->getId());  ( I added code to register copied milestone id) (edited) 
And after create task for copied project, I get task and replaced milestone to new milestone
$tasks = get_post_meta($theClone['ID'], '_upstream_project_tasks', true);
               if (count($tasks) > 0) {
                   foreach ($tasks as &$task) {
                       if (isset($task['milestone'])) {
                           $new_milestone_id = get_post_meta($task['milestone'], 'upst_new_id', true);
                           $task['milestone'] = $new_milestone_id;
                       }
                   }
                   update_post_meta($theClone['ID'], '_upstream_project_tasks', $tasks);
               }
on UpStream-Copy-Project / library / plugin.php : Line 344  on doClone() function
But it doesn't work correctly and it's difficult to debug it now,
When you have some spare time, I'd like you to help me for me.

**Comment by andergmartins** [comment]
@sergeidevstar001 I tried to reproduce the bug but I wasn't able. All the tasks have their milestone linked after copying. Am I missing anything? Please, could you confirm you see and can reproduce the bug?

**Comment by sergeidevstar001** [comment]
@andergmartins 
Original _upstream_project_tasks : include milestones but it's original milestones
after copied tasks, it remain original milestones.
But all milestones are clone, so it's different with original milestones.
So it cause problem on task (didn't select correct milestone id)

**Comment by andergmartins** [comment]
Thanks @sergeidevstar001 I think that doesn't require the NewId in the Milestone, you can just make the copyMilestones return a list with the mapped ids. Please, could you try applying this patch?
[fix-issue-788.patch.zip](https://github.com/upstreamplugin/UpStream/files/3308065/fix-issue-788.patch.zip)

**Comment by sergeidevstar001** [comment]
I got it, Thanks.

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
I think there are some problems on my code
if ( ! empty($newMilestonesIdList)) {
                    $tasks = get_post_meta($theClone['ID'], '_upstream_project_tasks', true);
                    if (count($tasks) > 0) {
                        foreach ($tasks as &$task) {
                            if (isset($task['milestone']) && isset($newMilestonesIdList[$task['milestone']])) {
                                $task['milestone'] = $newMilestonesIdList[$task['milestone']];
                            }
                        }
                        update_post_meta($theClone['ID'], '_upstream_project_tasks', $tasks);
                    }
                }

**Comment by sergeidevstar001** [comment]
I found problem.
get_post_meta() use cache, so after insert meta data, it can't get meta data with get_post_meta() in ajax process area.
foreach ($meta as $metaValue) {
                            $wpdb->insert($wpdb->prefix . 'postmeta', [
                                'post_id'    => $theClone['ID'],
                                'meta_key'   => $metaKey,
                                'meta_value' => $metaValue,
                            ]);
                        }

Will try to find solution.

**Comment by sergeidevstar001** [comment]
Fixed :)

**Comment by andergmartins** [comment]
Thanks, good job @sergeidevstar001
