### ISSUE TITLE
Activity is no longer human-readable

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#791]
Looks like we broke something recently ...

Old:
<img width="621" alt="project-activity" src="https://user-images.githubusercontent.com/3868028/58735468-8172e800-83c8-11e9-8e9b-dd8c6735cd05.png">

New:
<img width="798" alt="Screen Shot 2019-05-31 at 5 20 22 PM" src="https://user-images.githubusercontent.com/3868028/58735478-88015f80-83c8-11e9-9ef8-3b9e1881fc01.png">

This is the "Activity" tab in the admin area of projects

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I checked it on my localhost, but it works good.
I'm using development repository.
![image](https://user-images.githubusercontent.com/39214560/58741623-d278ef80-844d-11e9-9c3b-722f1705a42c.png)
Could you check master repository again for me?

**Comment by stevejburge** [comment]
OK, thanks. I'll reopen if I can create it again
