### ISSUE TITLE
Show the default order of Milestones

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#793]
So you can order Milestones in the admin:
<img width="812" alt="Screen Shot 2019-06-03 at 10 11 13 AM" src="https://user-images.githubusercontent.com/3868028/58808408-f839fc00-85e7-11e9-92c2-302a6bb25d1d.png">

But there's no way to see that ordering on the front of the site in the "Milestones" table:
<img width="613" alt="Screen Shot 2019-06-03 at 10 11 54 AM" src="https://user-images.githubusercontent.com/3868028/58808443-0d168f80-85e8-11e9-9cc5-5630dc7e005b.png">

Maybe we need an ordering column (1,2,3,4,5) in the left of the table

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I fixed it.
