### ISSUE TITLE
Categories don't show on Projects in the frontend 

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#794]
Step 1. Create Category custom field and add to project

<img width="915" alt="Screen Shot 2019-06-04 at 1 51 19 PM" src="https://user-images.githubusercontent.com/3868028/58901820-e9c70f80-86cf-11e9-9f37-c589b6de9361.png">

Step 2. Add a category to a project

<img width="636" alt="Screen Shot 2019-06-04 at 1 52 16 PM" src="https://user-images.githubusercontent.com/3868028/58901933-27c43380-86d0-11e9-9aa3-85225b9da419.png">

Step 3. Category doesn't show on the frontend:

<img width="1146" alt="Screen Shot 2019-06-04 at 1 53 51 PM" src="https://user-images.githubusercontent.com/3868028/58901972-3dd1f400-86d0-11e9-8aaf-daa2a8fc5124.png">

**Comment by sergeidevstar001** [comment]
I think it's related with #775.
Recently it saves to meta_key on Database, but it's wrong now.
Will debug all and will fix it.

**Comment by sergeidevstar001** [comment]
Problem : $project->categories doesn't exist
![image](https://user-images.githubusercontent.com/39214560/59110034-ce2e6400-8970-11e9-8fe9-9a2a488953d3.png)
It can be get by custom field category slug ($project->catcustom)
![image](https://user-images.githubusercontent.com/39214560/59110178-177eb380-8971-11e9-8269-905e06ab5b01.png)
But it's dynamic field, so I'm finding solution how to get it to get category for project.

**Comment by sergeidevstar001** [comment]
Problem: it didn't get custom categories correctly on project list page
UpStream-Custom-Fields / CustomFields / Pages / Project.php : LINE 1464
![image](https://user-images.githubusercontent.com/39214560/59111699-21ee7c80-8974-11e9-8170-f4b68c2a16c4.png)
$value : it's wrong
But it need to debug CustomFields / Fields / Category.php, so it need some time to fix current issue.

**Comment by sergeidevstar001** [comment]
![image](https://user-images.githubusercontent.com/39214560/59180894-a3265900-8b98-11e9-8f08-aa5291e92559.png)
UpStream-Custom-Fields / CustomFields / Pages / Project.php : LINE 1464
When $value is not array, it appear problem.
So I'm going to add some code for validation.

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by stevejburge** [comment]
This didn't go well

<img width="444" alt="Screen Shot 2019-06-28 at 11 35 24 AM" src="https://user-images.githubusercontent.com/3868028/60353822-da6a7780-9998-11e9-9b39-431a8fbe0a5c.png">

**Comment by andergmartins** [comment]
The related commit: https://github.com/upstreamplugin/UpStream-Custom-Fields/commit/4c011837f2bc7f1ade3d6ad01513db73e59767e2

**Comment by sergeidevstar001** [comment]
Fixed
