### ISSUE TITLE
Keep the modal window open

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#796]
> If you have the TASK screen open and accidently click off to the side, the window closes without saving any data. This happens on all screens (Project, Milestones, Tasks) you open to edit and click off the screen.
> 
> Is it possible for this not to happen and to close the TASK/MILESTONE/PROJECT edit screen you have to click one of the buttons (DELETE, CANCEL or SAVE) on the edit screen?

![image003](https://user-images.githubusercontent.com/3868028/58959269-b8535000-8772-11e9-92a5-15655f239e18.jpg)

**Comment by sergeidevstar001** [comment]
Solution: 
 $("#modal").modal({
        backdrop: "static",
        keyboard: false
});
data-backdrop="static" data-keyboard="false"
Solution Link : https://stackoverflow.com/questions/22207377/disable-click-outside-of-bootstrap-modal-area-to-close-modal#answers-header
But it doesn't work correctly on my localhost.
Will try to find another solution

**Comment by sergeidevstar001** [comment]
Fixed
