### ISSUE TITLE
Show how many search results are returned

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#797]
We had a request to show the number of results when using filters. For example: "12 Tasks match this search". It could be up by the filters:
![image001](https://user-images.githubusercontent.com/3868028/59033066-c9b16080-8835-11e9-9da5-728955b21949.jpg)

Or perhaps under the table, as in spreadsheet:
![image001](https://user-images.githubusercontent.com/3868028/59033084-d5048c00-8835-11e9-920c-c28f33429fa2.png)

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I think it's easy to get search results count.
Could you tell me where do you want to show it?

**Comment by stevejburge** [comment]
@sergeidevstar001 Good question. Maybe like Excel in the bottom left corner?

**Comment by sergeidevstar001** [comment]
Fixed
