### ISSUE TITLE
2 Users Editing The Same Project (Frontend) at the same time overwrite each other

### ISSUE THREAD

**Issue by oraclerob** [upstreamplugin/UpStream#798]
## Expected Behavior

There should be an OVN (object version number) assigned to the latest record. Before saving any updates, this should be checked and if the OVN has changed with the one in memory, mark the record as "stale" and report that the user needs to re-query as the data has changed.

UPDATE: Wordpress has built in functionality to do this - I've used the wp_set_post_lock( int $post_id ) to test this and have a prototype going for my customer.

## Current Behavior

2 Users editing the same project in the Frontend overwrite each other's changes completely. This should not be allowed to occur. We need the data to be read consistent and concurrent access.

*****This is occurring in the Frontend - Backend has a lock ****

## Possible Solution

Use wp_set_post_lock( int $post_id ) and check it before any updates occur.

## Steps to Reproduce (for bugs)

1. Get 2 users to open up the same project (Frontend).
2. Both make different changes. First user saves, the second user saves after the first user.
3. See how the first user's changes are completely overwritten.

**Comment by oraclerob** [comment]
I can't see any use of the wp_set_post_lock function when a user goes to edit a project. 

The class-up-frontend-process.php program is calling:
 // Update the post into the database
            wp_update_post($post);

Without checking any lock or setting from an edit.

**Comment by stevejburge** [comment]
Solution is here thanks to @oraclerob https://github.com/upstreamplugin/UpStream-Frontend-Edit/pull/131
