### ISSUE TITLE
Project project is always 0 for a copied project

### ISSUE THREAD

**Issue by andergmartins** [upstreamplugin/UpStream#801]
## Expected Behavior

Copied projects have all the tasks copied, including the % of progress for each one. So the total project progress should reflect that data, being the same from the original project.

## Current Behavior

If you copy a project which progress is 40% (that is true for any value), the copied project has a progress equals 0. It seems like editing/saving the project or editing tasks don't refresh the project's progress. Doesn't matter if the project is a draft or if is published.

## Demo site
You can test on this demo site (temporarily available):

Login: http://busy-mongoose.w5.wpsandbox.pro/wp-admin/ 
Username: demo 
Password: 8wNT2o5o5HTa

## Screenshots

<img width="1104" alt="Screen Shot 2019-06-11 at 17 43 00" src="https://user-images.githubusercontent.com/407131/59305328-6f1e6700-8c70-11e9-84e2-36d66057ffe2.png">
<img width="1016" alt="Screen Shot 2019-06-11 at 17 43 53" src="https://user-images.githubusercontent.com/407131/59305369-82c9cd80-8c70-11e9-8736-808bb4a89d54.png">
<img width="1043" alt="Screen Shot 2019-06-11 at 17 44 21" src="https://user-images.githubusercontent.com/407131/59305394-9117e980-8c70-11e9-83e5-e03764acc7ff.png">

**Comment by sergeidevstar001** [comment]
I didn't found where can I copy project, sorry.
Could you tell me where can I copy project for me?
![image](https://user-images.githubusercontent.com/39214560/59396293-a862ee00-8dba-11e9-8df9-7907899e5d09.png)

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by andergmartins** [comment]
@sergeidevstar001 cool, thanks. Please, always mention the number of the issue on the commit message so we an keep track of what changed for each issue. Thanks.
