### ISSUE TITLE
Broken dropdown links in top-right corner

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#82]
We broke the dropdown links in 1.10

![screen shot 2017-06-29 at 11 56 26 am](https://user-images.githubusercontent.com/26938537/27697359-ff77f176-5cc1-11e7-85d0-2570cfbcdaa8.png)
This is highly likely to be related to the same errors as the modals

**Comment by deenison** [comment]
This issue was solved on the [v1.10.1 - Patch Release](https://github.com/upstreamplugin/UpStream/pull/84).
