### ISSUE TITLE
Checkboxes and radio buttons don't save

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#823]
On the demo sites, you can see these don't save correctly

<img width="627" alt="Screen Shot 2019-06-28 at 11 28 34 AM" src="https://user-images.githubusercontent.com/3868028/60353417-fde0f280-9997-11e9-9031-fd591d9567f1.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I think it will be fine after merge #794 , because it related with #794 
I already fixed it.

**Comment by sergeidevstar001** [comment]
Fixed it by #775
