### ISSUE TITLE
Block Client Users from accessing the "Projects" area

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#827]
At the moment, this is what Client Users see in the WordPress admin:
<img width="285" alt="Screen Shot 2019-07-01 at 9 23 28 AM" src="https://user-images.githubusercontent.com/3868028/60440055-f3199e00-9be1-11e9-9460-da9ef0d5b765.png">

They should not have access to the "Projects" screen

**Comment by andergmartins** [comment]
@sergeidevstar001 it is not working yet. It only disappears after I enter the Projects page. But appears when I'm on the dashboard or profile page.

<img width="998" alt="Screen Shot 2019-07-30 at 14 53 38" src="https://user-images.githubusercontent.com/407131/62152995-06e81b00-b2da-11e9-8448-c97790e106a5.png">

<img width="965" alt="Screen Shot 2019-07-30 at 14 54 04" src="https://user-images.githubusercontent.com/407131/62152967-f9329580-b2d9-11e9-8219-3171090b29d4.png">

**Comment by sergeidevstar001** [comment]
Hi, @andergmartins 
I don't understand your screenshot, because it have to work with current code.
May I check the site admin panel?
