### ISSUE TITLE
Frontend custom fields do not sort using table arrows

### ISSUE THREAD

**Issue by oraclerob** [upstreamplugin/UpStream#836]
## Expected Behavior
The up/down arrows should sort when using custom fields.

## Current Behavior
Nothing happens, the arrows do not work.

## Steps to Reproduce (for bugs)
Add some custom fields and try to click on the arrows - they don't work. As below:

![image](https://user-images.githubusercontent.com/11176397/60866031-eb996b00-a259-11e9-8a9b-138356eaa154.png)

**Comment by stevejburge** [comment]
Related: https://github.com/upstreamplugin/UpStream-Custom-Fields/issues/70

I think this fix is waiting to be committed

@sergeidevstar001 Can you double-check?

**Comment by oraclerob** [comment]
Agreed, @stevejburge there is a pull request #775 for this. Not sure why this didn't make the release? Be good if it is actually solved I can then merge it for our customer.

**Comment by oraclerob** [comment]
@stevejburge I've put the committed patch into my customer's site and it doesn't work. Yes, the arrows now go up and down now however nothing is actually sorted in the table. This should be reopened before merging into the release.

**Comment by oraclerob** [comment]
Now I'm confused @stevejburge . I've updated to v1.5 of the Custom Fields and now this is fixed - yet the commit to fix it is still in development.

**Comment by stevejburge** [comment]
That's good to hear @oraclerob. Sorry, we're onboarding a new developer and this last release had a couple of hiccups. Still - better to have two solutions than none :)
