### ISSUE TITLE
Add Delete buttons to the Frontend

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#839]
For example, Tasks, Milestones, Bugs need a Delete button:
<img width="620" alt="Screen Shot 2019-07-13 at 6 43 03 PM" src="https://user-images.githubusercontent.com/3868028/61174273-2541dd00-a59e-11e9-964b-5956a8ae0ba0.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I think before I already worked it.
Anyway I will fix it for you.

**Comment by stevejburge** [comment]
@sergeidevstar001 We added Delete buttons only for Projects

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
It was #763 : only for Project
Sorry my misunderstanding...
Will fix it today.
