### ISSUE TITLE
Remove the default Categories and Tags

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#842]
This is a relic from before the Custom Fields extension. This needs 4 steps:

1. Let's remove Categories as an option from the admin:
<img width="442" alt="Screen Shot 2019-07-16 at 5 39 24 PM" src="https://user-images.githubusercontent.com/3868028/61308490-ab556200-a7f0-11e9-872c-08f1f94a005d.png">

2. And remove here:
<img width="304" alt="Screen Shot 2019-07-16 at 5 39 53 PM" src="https://user-images.githubusercontent.com/3868028/61308538-bf00c880-a7f0-11e9-8c7a-d29504ba4177.png">

3. And remove from the frontend:
<img width="1116" alt="Screen Shot 2019-07-16 at 5 37 02 PM" src="https://user-images.githubusercontent.com/3868028/61308502-b14b4300-a7f0-11e9-9653-7facd3592c18.png">

4. Finally, we can hide the "Categories" and "Tags" fields for people who don't have Custom Fields installed.

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
It's difficult to remove default categories and tags tab.
I fixed (1.) by following code.
            unset($defaults['taxonomy-project_category']);
            unset($defaults['taxonomy-upstream_tag']);
But didn't fixed (2.), (3.) yet at yesterday.
