### ISSUE TITLE
Usernames need wrapping in Projects table

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#850]
<img width="816" alt="Screen Shot 2019-07-24 at 7 10 50 PM" src="https://user-images.githubusercontent.com/3868028/61814142-abd0a700-ae47-11e9-83e0-972bc1bc7725.png">

**Comment by andergmartins** [comment]
@sergeidevstar001 Sorry, but this is the result after your commit:

<img width="989" alt="Screen Shot 2019-07-26 at 11 50 00" src="https://user-images.githubusercontent.com/407131/61960527-04b15400-af9c-11e9-9f1b-75d4688ae6e5.png">

I'm not sure what you did to fix there.

@stevejburge Please, could you clarify a little more what this issue means? Di you mean wrapping the text within a tag so we can apply a style like this to wrap it?

<img width="1045" alt="Screen Shot 2019-07-26 at 11 53 10" src="https://user-images.githubusercontent.com/407131/61960650-3d512d80-af9c-11e9-93ac-1011aaddc64a.png">

**Comment by sergeidevstar001** [comment]
I think it must be display like it.
![image](https://user-images.githubusercontent.com/39214560/61963339-eed47b00-affd-11e9-8595-68b2602bf762.png)

**Comment by andergmartins** [comment]
Ah, great, that makes sense. Thanks @sergeidevstar001.
