### ISSUE TITLE
Date sorting is incorrect

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#854]
Try sorting by Start Date or End Date. The results are wrong:

<img width="479" alt="Screen Shot 2019-07-25 at 8 48 28 AM" src="https://user-images.githubusercontent.com/3868028/61852164-153cce00-aeb9-11e9-9319-e0343b96ec6a.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
Problem : It used default string sort function.
I will find solution if date sorting function exist

**Comment by sergeidevstar001** [comment]
My solution: August 1 need to change with August 01

**Comment by sergeidevstar001** [comment]
I fixed it.
Before it used Wordpress default date format, so it was "F j, Y".
I changed it to "F d, Y"
