### ISSUE TITLE
Country field doesn't work on Clients

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#855]
Create a Country field:
<img width="930" alt="Screen Shot 2019-07-25 at 8 57 57 AM" src="https://user-images.githubusercontent.com/3868028/61852686-5e415200-aeba-11e9-8700-04c06c6424c7.png">

It won't show for Clients, even if enabled for them:
<img width="299" alt="Screen Shot 2019-07-25 at 8 58 54 AM" src="https://user-images.githubusercontent.com/3868028/61852721-73b67c00-aeba-11e9-98aa-bf9400bd8bf1.png">

**Comment by sergeidevstar001** [comment]
Hi, @stevejburge 
I think it works good.
I tested it on several dev servers.
When you have some spare time, please check it for me.
I think when you check it, you may used old source...

**Comment by stevejburge** [comment]
Sorry, not working in your initial 1.25.2 package
