### ISSUE TITLE
Some date formats cause problems with modals

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream#862]
Step 1. Translate your site into German
Step 2. Choose the new default date format:

<img width="516" alt="Screen Shot 2019-07-29 at 11 04 15 AM" src="https://user-images.githubusercontent.com/3868028/62039990-a6c97a00-b1f0-11e9-84d7-589ba9611ec8.png">

Step 3. Try to edit a Task on the frontend and the Modal just spins:

<img width="1001" alt="Screen Shot 2019-07-29 at 11 04 44 AM" src="https://user-images.githubusercontent.com/3868028/62040031-b943b380-b1f0-11e9-89c1-bf5a80b90361.png">

Here's the console error:

<img width="1087" alt="Screen Shot 2019-07-29 at 11 05 24 AM" src="https://user-images.githubusercontent.com/3868028/62040072-cb255680-b1f0-11e9-8dbb-16e3b0e1d333.png">

**Comment by sergeidevstar001** [comment]
Problem : it doesn't provide "j. F Y" format on current datepicker.
Solution : need convert it with default format.
