### ISSUE TITLE
Need some more details on the avatar

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#87]
It's literally impossible to identify Client User or Project Members if they don't have an avatar

There needs to be information under their photo, or more likely in a pop-up
![members](https://user-images.githubusercontent.com/26938537/27738039-4a446854-5d78-11e7-8ed4-91afdf023133.png)

**Comment by deenison** [comment]
This issue seemed to be solved on the [v1.10.3](https://github.com/upstreamplugin/UpStream/releases/tag/v1.10.3) release.
