### ISSUE TITLE
Copy Projects doesn't copy any field values to the new project

### ISSUE THREAD

**Issue by oraclerob** [upstreamplugin/UpStream#899]
Please see:

https://github.com/upstreamplugin/UpStream-Copy-Project/issues/19

I've opened another issue here as the bug is in a module in this repo.

## Expected Behavior

Copy Project should copy all the fields to the new project.

## Current Behavior

All fields are blank.

## Possible Solution

https://github.com/upstreamplugin/UpStream-Copy-Project/issues/19

## Your Environment

1.29.3

**Comment by westbourneintl** [comment]
Okay, I have fixed it and will push the update later today

Thanks, Rob!

**Comment by oraclerob** [comment]
Adding a Milestone (front and back end) isn't working either. When you add it - it disappears. This might be related, but please check. Thanks.

**Comment by oraclerob** [comment]
@westbourneintl - I've just completed the 1.29.9 update and this has fixed the milestone issue. However all the custom fields disappeared from the frontend - I needed to update them all manually to get them back.

**Comment by westbourneintl** [comment]
Thanks for letting me know.  We fixed the custom fields bug.
