### ISSUE TITLE
Discussion for tasks / bugs

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#96]
This is a good idea:
https://wordpress.org/support/topic/reply-option-in-bugstasks/#post-9291076

Tasks, bugs, and files could definitely benefit from discussion areas

**Comment by upstreamplugin** [comment]
Perhaps this could be done through https://github.com/upstreamplugin/UpStream/issues/50

**Comment by upstreamplugin** [comment]
One more request for this:
"Is it possible for my customers to comment on uploaded images?"

**Comment by deenison** [comment]
On hold in favor of issue #142.
