### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by upstreamplugin** [upstreamplugin/UpStream#99]
Let's fix these for the next release
![project-translate](https://user-images.githubusercontent.com/26938537/28018317-d96974e6-654a-11e7-9788-51f1363ff7eb.jpg)

![loco-translate](https://user-images.githubusercontent.com/26938537/28018350-f1c4e296-654a-11e7-8b83-7e0d869761f3.jpg)

**Comment by upstreamplugin** [comment]
More here:

![add-bug-translation](https://user-images.githubusercontent.com/26938537/28021490-0f625242-6556-11e7-819d-47ecb7f0543d.jpg)
![add-file-translation](https://user-images.githubusercontent.com/26938537/28021494-0f6dd43c-6556-11e7-8b4b-0742e9fd0dbc.jpg)
![add-message-translation](https://user-images.githubusercontent.com/26938537/28021489-0f6114a4-6556-11e7-928f-24d7601de749.jpg)
![delete-messages-translation](https://user-images.githubusercontent.com/26938537/28021492-0f66dcf4-6556-11e7-8bed-7e83149e1daf.jpg)
![frontend-editor-translate](https://user-images.githubusercontent.com/26938537/28021493-0f67b44e-6556-11e7-9d26-e1824bae43e2.png)
![timetable](https://user-images.githubusercontent.com/26938537/28021491-0f6697c6-6556-11e7-8a9c-a8ba82b703fc.png)

**Comment by deenison** [comment]
Our language `pot` file definitely needs an update.

**Comment by deenison** [comment]
Most of the strings mentioned can be translatable on the Frontend Edit plugin rather than UpStream itself.
